default:
  - build:
      - checkGivenSemanticVersion:
          checkSemanticVersion:
      - getSemanticVersion:
          gitCalculateSemanticVersion:
      - getImageName:
          containerConstructImageName:
      - artifacts:
          - containerBuildImage:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              target: tester
              extraArgs:
                - --build-arg
                - VERSION=${var.semanticVersion}
          - containerBuildImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}
              target: runner
              extraArgs:
                - --build-arg
                - VERSION=${var.semanticVersion}
              pullAlways: false
  - test:
      - unit:
          - script: mkdir -p test_reports
          - pythonContainerTest:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              testDirectory: tests
              packageManager: ''
              pullAlways: false
              withCoverage: true
              removeLocalImage: false
      - lint:
          - script: mkdir -p test_reports
          - pythonContainerLint:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
              removeLocalImage: false
          - pythonContainerTypeCheck:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
              removeLocalImage: false
  - verify:
      - publishSbom:
          - securityPublishSbom:
  - publish:
      - artifacts:
          - containerPublishImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}
              removeLocalImage: false
  - clean:
      - images:
          - cleanupImages:
              targets:
                  - image://${var.containerImageName}-tester:${var.semanticVersion}
                  - image://${var.containerImageName}-aws:${var.semanticVersion}

variables:
  project: pyflexplot
  solution: dispersionmodelling
  notifyOnNightlyFailure: p_dispersionmodelling@meteoswiss.ch
