default:
  - build:
      - checkGivenSemanticVersion:
          checkSemanticVersion:
      - getSemanticVersion:
          gitCalculateSemanticVersion:
      - getImageName:
          containerConstructImageName:
      - artifacts:
          - containerBuildImage:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              target: tester
              extraArgs:
                - --build-arg
                - VERSION=${var.semanticVersion}
          - containerBuildImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}
              target: runner
              extraArgs:
                - --build-arg
                - VERSION=${var.semanticVersion}
              pullAlways: false
  - test:
      - unit:
          - script: mkdir -p test_reports
          - pythonContainerTest:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              testDirectory: tests
              packageManager: ''
              pullAlways: false
              withCoverage: true
      - lint:
          - script: mkdir -p test_reports
          - pythonContainerLint:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
              removeLocalImage: false
          - pythonContainerTypeCheck:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
              removeLocalImage: false
  - verify:
      - securityScan:
          - securityReport:
              format: [ 'html', 'sbom', 'table', 'print' ]
              severity: [ 'CRITICAL', 'HIGH' ]
              target: file://poetry.lock
              qualityGate:
                threshold: 5
                criticalFactor: 5
                highFactor: 1
      - publishSbom:
          - securityPublishSbom:
  - publish:
      - artifacts:
          - containerPublishImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}

  - deploy:
      - pypi:
          pythonPublishPackage:
            setPackageVersion: False
            pythonImageName: '3.10'
            pullAlways: false
  - clean:
      - images:
          script: |
            if test -n "${var.semanticVersion}"; then
              podman image rm -f $(podman image ls -q \
                -f "label=ch.meteoswiss.project=${var.project}-${var.semanticVersion}") || :
            fi

variables:
  project: pyflexplot
  # default full image name, useful when running tasks locally
  image: ${var.containerImageName}:${var.semanticVersion}
  solution: dispersionmodelling
  notifyOnNightlyFailure: p_dispersionmodelling@meteoswiss.ch
