default:
  - build:
      - checkGivenSemanticVersion:
          - checkSemanticVersion:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - getImageName:
          - containerConstructImageName:
      - artifacts:
          - containerBuildImage:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              target: tester
              extraArgs: &buildArtifactExtraArgs
                - --build-arg
                - VERSION=${var.semanticVersion}
                - --build-arg
                - BUILD_ID=${var.buildId}
          - containerBuildImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}
              target: runner
              extraArgs: *buildArtifactExtraArgs
              pullAlways: false
  - test:
      - unit:
          - script: mkdir -p test_reports
          - pythonContainerTest:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              pullAlways: false
              packageManager: ''
              removeLocalImage: false
              testDirectory: tests
      - lint:
          - script: mkdir -p test_reports
          - pythonContainerLint:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              pullAlways: false
              packageManager: ''
              removeLocalImage: false
          - pythonContainerTypeCheck:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              pullAlways: false
              packageManager: ''
              removeLocalImage: false
  - verify:
      - publishSbom:
          - securityPublishSbom:
  - publish:
      - artifacts:
          - containerPublishImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}
              removeLocalImage: false
  - clean:
      - images:
          cleanupImages:
              targets:
                  - image://${var.containerImageName}-tester:${var.semanticVersion}
                  - image://${var.containerImageName}-aws:${var.semanticVersion}

variables:
  solution: dispersionmodelling
  project: pyflexplot
  notifyOnNightlyFailure: p_dispersionmodelling@meteoswiss.ch
  semanticVersion: 0.0.0  # is overwritten in Jenkins
  buildId: n/a # is overwritten in Jenkins
  containerImageName: docker-intern-nexus.meteoswiss.ch/${var.solution}/${var.project}
