
[isort]
force_grid_wrap=0
include_trailing_comma=True
line_length=88
multi_line_output=3
use_parentheses=True

[flake8]
exclude = docs
max-line-length = 88
ignore =
    E203, # Allow whitespace before ':'
          # See https://github.com/PyCQA/pycodestyle/issues/373
    W503, # Allow line break before binary operator (PEP 8-compatible)
    I002, # Don't check for isort configuration

[pytest]
collect_ignore = ["setup.py"]
testpaths = tests
addopts =
    -s
    -rs
    --color=no

[tox]
envlist =
    py37
    flake8

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
install_command =
    pip install -U {opts} {packages}
deps =
    pytest
# To use pinned package versions, create a requirements.txt:
#    -r{toxinidir}/requirements.txt
commands =
    pytest --basetemp={envtmpdir} --junitxml=junit-{envname}.xml

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 src tests

