pipeline {
    options {
    // the variable $WORKSPACE is assigned dynamically at the beginning of every stage
    // and might change depending on the number of concurrent builds active.
    // We can only allow 1 concurrent build to have a consistent access to $WORKSPACE
    // Otherwise we should use stash/unstash for the miniconda installation
        disableConcurrentBuilds()
    }
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                bash tools/setup_miniconda.sh -p ${WORKSPACE}
                '''
            }
        }
        stage('build unpinned') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate
                bash tools/setup_env.sh -n pyflexplot -u
                conda activate pyflexplot
                pip install --no-deps .
                '''
            }
        }
        stage('test unpinned') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate pyflexplot
                pytest tests
                '''
            }
        }
        stage('build pinned') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate
                bash tools/setup_env.sh -n pyflexplot-pinned
                conda activate pyflexplot-pinned
                pip install --no-deps .
                '''
            }
        }
        stage('test pinned') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate pyflexplot-pinned
                pytest tests
                '''
            }
        }
    }
}
