# -*- coding: utf-8 -*-
"""
Test reference for pytest test.

tests/slow/pyflexplot/test_plots/shared.py
    ::Test_CloudArrivalTime
    ::test

Created by temporarily changing the parent class of
``Test_CloudArrivalTime``
from ``_TestBase`` to ``_CreateReference`` and running pytest.
"""

field_summary = {
    "fld": {
        "dtype": "float64",
        "n_nan": 659,
        "n_zero": 0,
        "nanmax": 10.0,
        "nanmax_nonzero": 10.0,
        "nanmean": 8.12128418549346,
        "nanmean_nonzero": 8.12128418549346,
        "nanmedian": 8.0,
        "nanmedian_nonzero": 8.0,
        "nanmin": 4.0,
        "nanmin_nonzero": 4.0,
        "shape": (30, 50),
    },
    "lat": {"dtype": "float32", "max": -0.42000008, "min": -3.3199997, "shape": (30,)},
    "lon": {"dtype": "float32", "max": 2.4799995, "min": -2.42, "shape": (50,)},
    "nc_meta_data": {
        "analysis": {"model": "cosmo2", "rotated_pole": True, "species_ids": [1, 2]},
        "dimensions": {
            "level": {"name": "level", "size": 3},
            "nageclass": {"name": "nageclass", "size": 1},
            "nchar": {"name": "nchar", "size": 45},
            "numpoint": {"name": "numpoint", "size": 1},
            "numspec": {"name": "numspec", "size": 2},
            "rlat": {"name": "rlat", "size": 30},
            "rlon": {"name": "rlon", "size": 50},
            "time": {"name": "time", "size": 11},
        },
        "ncattrs": {"dxout": 0.02, "dyout": 0.02},
        "variables": {
            "DD_spec001": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "DD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "density": 2500.0,
                    "dquer": 0.6,
                    "dryvel": 0.0015,
                    "dsigma": 0.3,
                    "f0": 0.0,
                    "henry": 0.0,
                    "long_name": "Cs-137_dry_deposition",
                    "reldiff": -9.9,
                    "units": "1e-12 kg " "m-2",
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "DD_spec002": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "DD_spec002",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "density": 2500.0,
                    "dquer": 0.6,
                    "dryvel": 0.0015,
                    "dsigma": 0.3,
                    "f0": 0.0,
                    "henry": 0.0,
                    "long_name": "I-131a_dry_deposition",
                    "reldiff": -9.9,
                    "units": "1e-12 kg " "m-2",
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "LAGE": {
                "dimensions": ["nageclass"],
                "name": "LAGE",
                "ncattrs": {"long_name": "age class", "units": "seconds"},
                "shape": [1],
            },
            "RELCOM": {
                "dimensions": ["numpoint", "nchar"],
                "name": "RELCOM",
                "ncattrs": {"long_name": "release " "point " "name"},
                "shape": [1, 45],
            },
            "RELEND": {
                "dimensions": ["numpoint"],
                "name": "RELEND",
                "ncattrs": {
                    "long_name": "release "
                    "end "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELKINDZ": {
                "dimensions": ["numpoint"],
                "name": "RELKINDZ",
                "ncattrs": {"long_name": "release " "kind"},
                "shape": [1],
            },
            "RELLAT1": {
                "dimensions": ["numpoint"],
                "name": "RELLAT1",
                "ncattrs": {
                    "long_name": "release " "latitude " "lower " "left " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLAT2": {
                "dimensions": ["numpoint"],
                "name": "RELLAT2",
                "ncattrs": {
                    "long_name": "release " "latitude " "upper " "right " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLNG1": {
                "dimensions": ["numpoint"],
                "name": "RELLNG1",
                "ncattrs": {
                    "long_name": "release " "longitude " "lower " "left " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELLNG2": {
                "dimensions": ["numpoint"],
                "name": "RELLNG2",
                "ncattrs": {
                    "long_name": "release " "longitude " "upper " "right " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELPART": {
                "dimensions": ["numpoint"],
                "name": "RELPART",
                "ncattrs": {"long_name": "number " "of " "release " "particles"},
                "shape": [1],
            },
            "RELSTART": {
                "dimensions": ["numpoint"],
                "name": "RELSTART",
                "ncattrs": {
                    "long_name": "release "
                    "start "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELXMASS": {
                "dimensions": ["numspec", "numpoint"],
                "name": "RELXMASS",
                "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                "shape": [2, 1],
            },
            "RELZZ1": {
                "dimensions": ["numpoint"],
                "name": "RELZZ1",
                "ncattrs": {
                    "long_name": "release " "height " "bottom",
                    "units": "meters",
                },
                "shape": [1],
            },
            "RELZZ2": {
                "dimensions": ["numpoint"],
                "name": "RELZZ2",
                "ncattrs": {"long_name": "release " "height " "top", "units": "meters"},
                "shape": [1],
            },
            "WD_spec001": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "WD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "dquer": 0.6,
                    "henry": 0.0,
                    "long_name": "Cs-137_wet_deposition",
                    "units": "1e-12 kg " "m-2",
                    "weta": 7e-05,
                    "wetb": 0.8,
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "WD_spec002": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "WD_spec002",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "dquer": 0.6,
                    "henry": 0.0,
                    "long_name": "I-131a_wet_deposition",
                    "units": "1e-12 kg " "m-2",
                    "weta": 7e-05,
                    "wetb": 0.8,
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "fptot": {
                "dimensions": ["numpoint", "rlat", "rlon"],
                "name": "fptot",
                "ncattrs": {
                    "coordinates": "lon lat",
                    "long_name": "total_footprint",
                    "sampling_height": "undefined",
                    "units": "ng kg-1",
                },
                "shape": [1, 30, 50],
            },
            "level": {
                "dimensions": ["level"],
                "name": "level",
                "ncattrs": {
                    "axis": "Z",
                    "description": "grid " "cell top",
                    "long_name": "height " "above " "ground",
                    "positive": "up",
                    "standard_name": "height",
                    "units": "meters",
                },
                "shape": [3],
            },
            "rlat": {
                "dimensions": ["rlat"],
                "name": "rlat",
                "ncattrs": {
                    "axis": "Y",
                    "description": "grid cell " "centers",
                    "long_name": "latitude in " "rotated " "pole grid",
                    "standard_name": "grid_latitude",
                    "units": "degrees",
                },
                "shape": [30],
            },
            "rlon": {
                "dimensions": ["rlon"],
                "name": "rlon",
                "ncattrs": {
                    "axis": "X",
                    "description": "grid cell " "centers",
                    "long_name": "longitude " "in rotated " "pole grid",
                    "standard_name": "grid_longitude",
                    "units": "degrees",
                },
                "shape": [50],
            },
            "rotated_pole": {
                "dimensions": {},
                "name": "rotated_pole",
                "ncattrs": {
                    "grid_mapping_name": "rotated_latitude_longitude",
                    "grid_north_pole_latitude": 43.0,
                    "grid_north_pole_longitude": -170.0,
                },
                "shape": {},
            },
            "spec001": {
                "dimensions": [
                    "nageclass",
                    "numpoint",
                    "time",
                    "level",
                    "rlat",
                    "rlon",
                ],
                "name": "spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "decay": 7.3265155e-10,
                    "long_name": "Cs-137",
                    "ohreact": -9.9e-09,
                    "spec_ass": -9,
                    "units": "ng kg-1",
                    "vsetaver": -0.0003866022,
                    "weightmolar": -9.99,
                },
                "shape": [1, 1, 11, 3, 30, 50],
            },
            "spec002": {
                "dimensions": [
                    "nageclass",
                    "numpoint",
                    "time",
                    "level",
                    "rlat",
                    "rlon",
                ],
                "name": "spec002",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "decay": 9.978277e-07,
                    "long_name": "I-131a",
                    "ohreact": -9.9e-09,
                    "spec_ass": -9,
                    "units": "ng kg-1",
                    "vsetaver": -0.0003866022,
                    "weightmolar": -9.99,
                },
                "shape": [1, 1, 11, 3, 30, 50],
            },
            "time": {
                "dimensions": ["time"],
                "name": "time",
                "ncattrs": {
                    "calendar": "proleptic_gregorian",
                    "units": "seconds since " "2019-07-27 " "12:00",
                },
                "shape": [11],
            },
        },
    },
    "rotated_pole": True,
    "time_stats": {
        "max": 10.0,
        "mean": 3.449140633445033,
        "mean_nz": 4.6717423133235725,
        "median": 3.0,
        "median_nz": 5.0,
    },
    "type": "Field",
    "var_setups": [
        {
            "combine_species": True,
            "deposition_type": "none",
            "domain": "ch",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": 3,
            "ens_param_thr": 1e-09,
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "integrate": True,
            "lang": "de",
            "level": [0],
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "outfile": "plot.png",
            "plot_type": "ens_cloud_arrival_time",
            "simulation_type": "ensemble",
            "species_id": [1],
            "time": [0],
            "variable": "concentration",
        },
        {
            "combine_species": True,
            "deposition_type": "none",
            "domain": "ch",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": 3,
            "ens_param_thr": 1e-09,
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "integrate": True,
            "lang": "de",
            "level": [0],
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "outfile": "plot.png",
            "plot_type": "ens_cloud_arrival_time",
            "simulation_type": "ensemble",
            "species_id": [2],
            "time": [0],
            "variable": "concentration",
        },
    ],
}

plot_summary = {
    "ax_map": {"type": "MapAxesRotatedPole"},
    "boxes": {
        "method:Plot.fill_box_bottom": {
            "dx_unit": 0.00790513833992095,
            "dy_unit": 0.42334949883042644,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "small", "va": "top"},
                    "loc": {
                        "dx": -0.7,
                        "dx_unit": 0.00790513833992095,
                        "dy": 0.5,
                        "dy_unit": 0.42334949883042644,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.003952569169960475,
                        "x0": 0.009486166007905139,
                        "y": 0.7036553508187016,
                        "y0": 0.4919806014034883,
                    },
                    "replace_edge_spaces": False,
                    "s": "FLEXPART "
                    "basierend auf "
                    "COSMO-2, "
                    "2019-07-27 "
                    "12:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "small", "va": "top"},
                    "loc": {
                        "dx": 0.7,
                        "dx_unit": 0.00790513833992095,
                        "dy": 0.5,
                        "dy_unit": 0.42334949883042644,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.9960474308300395,
                        "x0": 0.9905138339920949,
                        "y": 0.7036553508187016,
                        "y0": 0.4919806014034883,
                    },
                    "replace_edge_spaces": False,
                    "s": "©MeteoSchweiz",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": None,
            "name": "bottom",
            "rect": [0.05, 0.031693612437452584, 0.980375, 0.018306387562547415],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_bottom": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.024085902988300087,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": -1.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.9470110134257399,
                        "y0": 0.97109691641404,
                    },
                    "replace_edge_spaces": False,
                    "s": "Freisetzung",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.06503193806841023,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschexponent:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 4.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.12524669553916046,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschkoeff.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 6.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.18546145300991068,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Sediment.-Geschw.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 9.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.2456762104806609,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Deposit.-Geschw.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 11.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.30589096795141113,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Halbwertszeit:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 14.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.3661057254221613,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Substanz:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.48653524036366175,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Totale " "Masse:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 21.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.5467499978344119,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Rate:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 24.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.6069647553051621,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ende:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 26.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.6671795127759124,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Start:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.7876090277174128,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": 'H$\\mathrm{\\"o}$he:',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 34.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.847823785188163,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": 'L$\\mathrm{\\"a}$nge:',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 36.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.9080385426589133,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Breite:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 39.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.9682533001296635,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.06503193806841023,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 4.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.12524669553916046,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 6.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.18546145300991068,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 9.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.2456762104806609,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 11.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.30589096795141113,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "30 / 8",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 14.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.3661057254221613,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137 + " "I-131a",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.48653524036366175,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "1e+09",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 21.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.5467499978344119,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "34722",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 24.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.6069647553051621,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-07-27 " "20:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 26.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.6671795127759124,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-07-27 " "12:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.7876090277174128,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "100",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 34.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.847823785188163,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "7$^\\circ$$\\,$0'$\\,$O " "(7.0000$^\\circ$$\\,$O)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 36.5,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.9080385426589133,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": "47$^\\circ$$\\,$0'$\\,$N " "(47.0000$^\\circ$$\\,$N)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 39.0,
                        "dy_unit": 0.024085902988300087,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.9682533001296635,
                        "y0": 0.028903083585960103,
                    },
                    "replace_edge_spaces": False,
                    "s": 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/bottom",
            "rect": [0.8366250000000001, 0.05, 0.19375, 0.32176497612585353],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_top": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.028393692677973367,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 1.008518107803392,
                        "y0": 0.9659275687864319,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ankunft " "(Stunden??)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 7.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.24702512629836829,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "0  $\\tt -$ " "2 ",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 10.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.3322062043322884,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "3  $\\tt -$ " "5 ",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 13.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.4173872823662085,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "6  $\\tt -$ " "8 ",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 16.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.5025683604001285,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "9  $\\tt -$ " "11",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.5877494384340487,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "12 $\\tt -$ " "14",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 22.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.6729305164679689,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "15 $\\tt -$ " "17",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 25.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.7581115945018889,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "18 $\\tt -$ " "20",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 28.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.843292672535809,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "21 $\\tt -$ " "23",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.9284737505697291,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "   $\\tt " "\\geq$ 24",
                    "type": "TextBoxElementText",
                },
                {
                    "ec": "black",
                    "fc": [0.8784313725490196, 0.7686274509803922, 0.6745098039215687],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 7.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.23566764922717892,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.8666666666666667, 0.4980392156862745, 0.8431372549019608],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 10.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.32084872726109903,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.38823529411764707, 0.0, 1.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 13.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.4060298052950191,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.39215686274509803, 0.6, 0.7803921568627451],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 16.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.49121088332893925,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [
                        0.13333333333333333,
                        0.5450980392156862,
                        0.13333333333333333,
                    ],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.5763919613628594,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.36470588235294116, 1.0, 0.00784313725490196],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 22.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.6615730393967795,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7803921568627451, 1.0, 0.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 25.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.7467541174306996,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [1.0, 0.9372549019607843, 0.2235294117647059],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 28.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.8319351954646197,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7843137254901961, 0.7843137254901961, 0.7843137254901961],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.1,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.9171162734985399,
                        "y0": 0.03407243121356804,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "kwargs": {
                        "markeredgecolor": "red",
                        "markeredgewidth": 1.5,
                        "markerfacecolor": "white",
                        "markersize": 7.5,
                    },
                    "loc": {
                        "dx": -8.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 2.45,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.17999999999999988,
                        "x0": 0.5,
                        "y": 0.10363697827460279,
                        "y0": 0.03407243121356804,
                    },
                    "m": "^",
                    "type": "TextBoxElementMarker",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.75,
                        "dy_unit": 0.028393692677973367,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.08376139340002142,
                        "y0": 0.03407243121356804,
                    },
                    "replace_edge_spaces": False,
                    "s": "Abgabeort",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/top",
            "rect": [
                0.8366250000000001,
                0.38726497612585353,
                0.19375,
                0.2729479426257271,
            ],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_left": {
            "dx_unit": 0.01,
            "dy_unit": 0.09071774974937706,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.09071774974937706,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.012,
                        "x0": 0.012,
                        "y": 0.8911387003007475,
                        "y0": 0.8911387003007475,
                    },
                    "replace_edge_spaces": False,
                    "s": "Wolkenankunftszeit " "auf 0$-$500 m " '$\\mathrm{\\"u}$.G.',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "center_baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.09071774974937706,
                        "ha": "left",
                        "loc": "ml",
                        "loc_x": "l",
                        "loc_y": "m",
                        "type": "TextBoxLocation",
                        "va": "center_baseline",
                        "x": 0.012,
                        "x0": 0.012,
                        "y": 0.5,
                        "y0": 0.5,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cloud: "
                    "$\\geq$ 1e-09 "
                    "Bq h m-3; "
                    "members: "
                    "$\\geq$ 3",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.09071774974937706,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.012,
                        "x0": 0.012,
                        "y": 0.10886129969925247,
                        "y0": 0.10886129969925247,
                    },
                    "replace_edge_spaces": False,
                    "s": "Aufsummiert "
                    '$\\mathrm{\\"u}$ber '
                    "3$\\,$h (seit "
                    "+00:00$\\,$h)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.09071774974937706,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.988,
                        "x0": 0.988,
                        "y": 0.8911387003007475,
                        "y0": 0.8911387003007475,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-07-27 " "15:00 UTC " "(+03:00$\\,$h)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.09071774974937706,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.988,
                        "x0": 0.988,
                        "y": 0.10886129969925247,
                        "y0": 0.10886129969925247,
                    },
                    "replace_edge_spaces": False,
                    "s": "03:00$\\,$h " "seit " "Freisetzungsbeginn",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/left",
            "rect": [0.05, 0.6757129187515806, 0.775, 0.08542980862522129],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_right": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.09071774974937706,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.0,
                        "dy_unit": 0.09071774974937706,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.8911387003007475,
                        "y0": 0.8911387003007475,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137 + " "I-131a",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.0,
                        "dy_unit": 0.09071774974937706,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.10886129969925247,
                        "y0": 0.10886129969925247,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort: " 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/right",
            "rect": [
                0.8366250000000001,
                0.6757129187515806,
                0.19375,
                0.08542980862522129,
            ],
            "type": "TextBoxAxes",
        },
    },
    "draw_colors": True,
    "draw_contours": False,
    "field": {
        "fld": {
            "dtype": "float64",
            "n_nan": 659,
            "n_zero": 0,
            "nanmax": 10.0,
            "nanmax_nonzero": 10.0,
            "nanmean": 8.12128418549346,
            "nanmean_nonzero": 8.12128418549346,
            "nanmedian": 8.0,
            "nanmedian_nonzero": 8.0,
            "nanmin": 4.0,
            "nanmin_nonzero": 4.0,
            "shape": [30, 50],
        },
        "lat": {
            "dtype": "float32",
            "max": -0.42000008,
            "min": -3.3199997,
            "shape": [30],
        },
        "lon": {"dtype": "float32", "max": 2.4799995, "min": -2.42, "shape": [50]},
        "nc_meta_data": {
            "analysis": {
                "model": "cosmo2",
                "rotated_pole": True,
                "species_ids": [1, 2],
            },
            "dimensions": {
                "level": {"name": "level", "size": 3},
                "nageclass": {"name": "nageclass", "size": 1},
                "nchar": {"name": "nchar", "size": 45},
                "numpoint": {"name": "numpoint", "size": 1},
                "numspec": {"name": "numspec", "size": 2},
                "rlat": {"name": "rlat", "size": 30},
                "rlon": {"name": "rlon", "size": 50},
                "time": {"name": "time", "size": 11},
            },
            "ncattrs": {"dxout": 0.02, "dyout": 0.02},
            "variables": {
                "DD_spec001": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "DD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "density": 2500.0,
                        "dquer": 0.6,
                        "dryvel": 0.0015,
                        "dsigma": 0.3,
                        "f0": 0.0,
                        "henry": 0.0,
                        "long_name": "Cs-137_dry_deposition",
                        "reldiff": -9.9,
                        "units": "1e-12 " "kg " "m-2",
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "DD_spec002": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "DD_spec002",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "density": 2500.0,
                        "dquer": 0.6,
                        "dryvel": 0.0015,
                        "dsigma": 0.3,
                        "f0": 0.0,
                        "henry": 0.0,
                        "long_name": "I-131a_dry_deposition",
                        "reldiff": -9.9,
                        "units": "1e-12 " "kg " "m-2",
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "LAGE": {
                    "dimensions": ["nageclass"],
                    "name": "LAGE",
                    "ncattrs": {"long_name": "age " "class", "units": "seconds"},
                    "shape": [1],
                },
                "RELCOM": {
                    "dimensions": ["numpoint", "nchar"],
                    "name": "RELCOM",
                    "ncattrs": {"long_name": "release " "point " "name"},
                    "shape": [1, 45],
                },
                "RELEND": {
                    "dimensions": ["numpoint"],
                    "name": "RELEND",
                    "ncattrs": {
                        "long_name": "release "
                        "end "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELKINDZ": {
                    "dimensions": ["numpoint"],
                    "name": "RELKINDZ",
                    "ncattrs": {"long_name": "release " "kind"},
                    "shape": [1],
                },
                "RELLAT1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT1",
                    "ncattrs": {
                        "long_name": "release " "latitude " "lower " "left " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLAT2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT2",
                    "ncattrs": {
                        "long_name": "release " "latitude " "upper " "right " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLNG1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG1",
                    "ncattrs": {
                        "long_name": "release " "longitude " "lower " "left " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELLNG2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG2",
                    "ncattrs": {
                        "long_name": "release " "longitude " "upper " "right " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELPART": {
                    "dimensions": ["numpoint"],
                    "name": "RELPART",
                    "ncattrs": {"long_name": "number " "of " "release " "particles"},
                    "shape": [1],
                },
                "RELSTART": {
                    "dimensions": ["numpoint"],
                    "name": "RELSTART",
                    "ncattrs": {
                        "long_name": "release "
                        "start "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELXMASS": {
                    "dimensions": ["numspec", "numpoint"],
                    "name": "RELXMASS",
                    "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                    "shape": [2, 1],
                },
                "RELZZ1": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ1",
                    "ncattrs": {
                        "long_name": "release " "height " "bottom",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "RELZZ2": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ2",
                    "ncattrs": {
                        "long_name": "release " "height " "top",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "WD_spec001": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "WD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "dquer": 0.6,
                        "henry": 0.0,
                        "long_name": "Cs-137_wet_deposition",
                        "units": "1e-12 " "kg " "m-2",
                        "weta": 7e-05,
                        "wetb": 0.8,
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "WD_spec002": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "WD_spec002",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "dquer": 0.6,
                        "henry": 0.0,
                        "long_name": "I-131a_wet_deposition",
                        "units": "1e-12 " "kg " "m-2",
                        "weta": 7e-05,
                        "wetb": 0.8,
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "fptot": {
                    "dimensions": ["numpoint", "rlat", "rlon"],
                    "name": "fptot",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "long_name": "total_footprint",
                        "sampling_height": "undefined",
                        "units": "ng " "kg-1",
                    },
                    "shape": [1, 30, 50],
                },
                "level": {
                    "dimensions": ["level"],
                    "name": "level",
                    "ncattrs": {
                        "axis": "Z",
                        "description": "grid " "cell " "top",
                        "long_name": "height " "above " "ground",
                        "positive": "up",
                        "standard_name": "height",
                        "units": "meters",
                    },
                    "shape": [3],
                },
                "rlat": {
                    "dimensions": ["rlat"],
                    "name": "rlat",
                    "ncattrs": {
                        "axis": "Y",
                        "description": "grid " "cell " "centers",
                        "long_name": "latitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_latitude",
                        "units": "degrees",
                    },
                    "shape": [30],
                },
                "rlon": {
                    "dimensions": ["rlon"],
                    "name": "rlon",
                    "ncattrs": {
                        "axis": "X",
                        "description": "grid " "cell " "centers",
                        "long_name": "longitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_longitude",
                        "units": "degrees",
                    },
                    "shape": [50],
                },
                "rotated_pole": {
                    "dimensions": {},
                    "name": "rotated_pole",
                    "ncattrs": {
                        "grid_mapping_name": "rotated_latitude_longitude",
                        "grid_north_pole_latitude": 43.0,
                        "grid_north_pole_longitude": -170.0,
                    },
                    "shape": {},
                },
                "spec001": {
                    "dimensions": [
                        "nageclass",
                        "numpoint",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "name": "spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "decay": 7.3265155e-10,
                        "long_name": "Cs-137",
                        "ohreact": -9.9e-09,
                        "spec_ass": -9,
                        "units": "ng " "kg-1",
                        "vsetaver": -0.0003866022,
                        "weightmolar": -9.99,
                    },
                    "shape": [1, 1, 11, 3, 30, 50],
                },
                "spec002": {
                    "dimensions": [
                        "nageclass",
                        "numpoint",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "name": "spec002",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "decay": 9.978277e-07,
                        "long_name": "I-131a",
                        "ohreact": -9.9e-09,
                        "spec_ass": -9,
                        "units": "ng " "kg-1",
                        "vsetaver": -0.0003866022,
                        "weightmolar": -9.99,
                    },
                    "shape": [1, 1, 11, 3, 30, 50],
                },
                "time": {
                    "dimensions": ["time"],
                    "name": "time",
                    "ncattrs": {
                        "calendar": "proleptic_gregorian",
                        "units": "seconds " "since " "2019-07-27 " "12:00",
                    },
                    "shape": [11],
                },
            },
        },
        "rotated_pole": True,
        "time_stats": {
            "max": 10.0,
            "mean": 3.449140633445033,
            "mean_nz": 4.6717423133235725,
            "median": 3.0,
            "median_nz": 5.0,
        },
        "type": "Field",
        "var_setups": [
            {
                "combine_species": True,
                "deposition_type": "none",
                "domain": "ch",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": 3,
                "ens_param_thr": 1e-09,
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "integrate": True,
                "lang": "de",
                "level": [0],
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "outfile": "plot.png",
                "plot_type": "ens_cloud_arrival_time",
                "simulation_type": "ensemble",
                "species_id": [1],
                "time": [0],
                "variable": "concentration",
            },
            {
                "combine_species": True,
                "deposition_type": "none",
                "domain": "ch",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": 3,
                "ens_param_thr": 1e-09,
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "integrate": True,
                "lang": "de",
                "level": [0],
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "outfile": "plot.png",
                "plot_type": "ens_cloud_arrival_time",
                "simulation_type": "ensemble",
                "species_id": [2],
                "time": [0],
                "variable": "concentration",
            },
        ],
    },
    "fig": {
        "axes": [
            {
                "bbox": {
                    "bounds": (60.0, 45.0, 930.0000000000001, 549.1916268764226),
                    "type": "TransformedBbox",
                },
                "type": "GeoAxesSubplot",
            },
            {
                "bbox": {
                    "bounds": (
                        60.0,
                        608.1416268764225,
                        930.0000000000001,
                        76.88682776269923,
                    ),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 608.1416268764225, 232.5, 76.88682776269923),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 348.53847851326816, 232.5, 245.6531483631544),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 45.0, 232.5, 289.58847851326817),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (60.0, 28.524251193707325, 1176.45, 16.475748806292675),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
        ],
        "bbox": {"bounds": (0.0, 0.0, 1200.0, 900.0), "type": "TransformedBbox"},
        "type": "Figure",
    },
    "map_conf": {
        "geo_res": "10m",
        "geo_res_cities": "10m",
        "geo_res_rivers": "10m",
        "lang": "de",
        "lw_frame": 1.0,
        "min_city_pop": 0,
        "ref_dist_conf": {
            "dist": 25,
            "pos": "bl",
            "type": "RefDistIndConf",
            "unit": "km",
        },
        "ref_dist_on": True,
        "rel_offset": [-0.02, 0.045],
        "type": "MapAxesConf",
        "zoom_fact": 3.2,
    },
    "mark_release_site": True,
    "type": "Plot",
}
