# -*- coding: utf-8 -*-
# flake8: noqa
"""
Test reference for pytest test.

tests/slow/pyflexplot/test_plots/shared.py
    ::Test_EnsMean_TotalDeposition
    ::test

Created by temporarily changing the parent class of
``Test_EnsMean_TotalDeposition``
from ``_TestBase`` to ``_TestCreateReference`` and running pytest.
"""

field_summary = {
    "type": "Field",
    "rotated_pole": True,
    "var_setups": [
        {
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "outfile": "plot.png",
            "plot_type": "ens_mean",
            "variable": "deposition",
            "deposition_type": "dry",
            "integrate": True,
            "combine_species": True,
            "simulation_type": "ensemble",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "lang": "en",
            "domain": "auto",
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "species_id": [1],
            "time": [10],
            "level": None,
        },
        {
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "outfile": "plot.png",
            "plot_type": "ens_mean",
            "variable": "deposition",
            "deposition_type": "dry",
            "integrate": True,
            "combine_species": True,
            "simulation_type": "ensemble",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "lang": "en",
            "domain": "auto",
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "species_id": [2],
            "time": [10],
            "level": None,
        },
        {
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "outfile": "plot.png",
            "plot_type": "ens_mean",
            "variable": "deposition",
            "deposition_type": "wet",
            "integrate": True,
            "combine_species": True,
            "simulation_type": "ensemble",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "lang": "en",
            "domain": "auto",
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "species_id": [1],
            "time": [10],
            "level": None,
        },
        {
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "outfile": "plot.png",
            "plot_type": "ens_mean",
            "variable": "deposition",
            "deposition_type": "wet",
            "integrate": True,
            "combine_species": True,
            "simulation_type": "ensemble",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "lang": "en",
            "domain": "auto",
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "species_id": [2],
            "time": [10],
            "level": None,
        },
    ],
    "time_stats": {
        "mean": 0.06554155,
        "median": 0.0,
        "mean_nz": 0.29628372,
        "median_nz": 0.0031997827,
        "max": 13.710873,
    },
    "nc_meta_data": {
        "ncattrs": {"dxout": 0.02, "dyout": 0.02},
        "dimensions": {
            "time": {"name": "time", "size": 11},
            "rlon": {"name": "rlon", "size": 50},
            "rlat": {"name": "rlat", "size": 30},
            "level": {"name": "level", "size": 3},
            "numspec": {"name": "numspec", "size": 2},
            "numpoint": {"name": "numpoint", "size": 1},
            "nageclass": {"name": "nageclass", "size": 1},
            "nchar": {"name": "nchar", "size": 45},
        },
        "variables": {
            "time": {
                "name": "time",
                "dimensions": ["time"],
                "shape": [11],
                "ncattrs": {
                    "units": "seconds since 2019-07-27 12:00",
                    "calendar": "proleptic_gregorian",
                },
            },
            "rlon": {
                "name": "rlon",
                "dimensions": ["rlon"],
                "shape": [50],
                "ncattrs": {
                    "long_name": "longitude in rotated pole grid",
                    "units": "degrees",
                    "standard_name": "grid_longitude",
                    "axis": "X",
                    "description": "grid cell centers",
                },
            },
            "rlat": {
                "name": "rlat",
                "dimensions": ["rlat"],
                "shape": [30],
                "ncattrs": {
                    "long_name": "latitude in rotated pole grid",
                    "units": "degrees",
                    "standard_name": "grid_latitude",
                    "axis": "Y",
                    "description": "grid cell centers",
                },
            },
            "level": {
                "name": "level",
                "dimensions": ["level"],
                "shape": [3],
                "ncattrs": {
                    "axis": "Z",
                    "units": "meters",
                    "positive": "up",
                    "standard_name": "height",
                    "long_name": "height above ground",
                    "description": "grid cell top",
                },
            },
            "rotated_pole": {
                "name": "rotated_pole",
                "dimensions": {},
                "shape": {},
                "ncattrs": {
                    "grid_mapping_name": "rotated_latitude_longitude",
                    "grid_north_pole_latitude": 43.0,
                    "grid_north_pole_longitude": -170.0,
                },
            },
            "RELCOM": {
                "name": "RELCOM",
                "dimensions": ["numpoint", "nchar"],
                "shape": [1, 45],
                "ncattrs": {"long_name": "release point name"},
            },
            "RELLNG1": {
                "name": "RELLNG1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_east",
                    "long_name": "release longitude lower left corner",
                },
            },
            "RELLNG2": {
                "name": "RELLNG2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_east",
                    "long_name": "release longitude upper right corner",
                },
            },
            "RELLAT1": {
                "name": "RELLAT1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_north",
                    "long_name": "release latitude lower left corner",
                },
            },
            "RELLAT2": {
                "name": "RELLAT2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_north",
                    "long_name": "release latitude upper right corner",
                },
            },
            "RELZZ1": {
                "name": "RELZZ1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"units": "meters", "long_name": "release height bottom"},
            },
            "RELZZ2": {
                "name": "RELZZ2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"units": "meters", "long_name": "release height top"},
            },
            "RELKINDZ": {
                "name": "RELKINDZ",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"long_name": "release kind"},
            },
            "RELSTART": {
                "name": "RELSTART",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "seconds",
                    "long_name": "release start relative to simulation start",
                },
            },
            "RELEND": {
                "name": "RELEND",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "seconds",
                    "long_name": "release end relative to simulation start",
                },
            },
            "RELPART": {
                "name": "RELPART",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"long_name": "number of release particles"},
            },
            "RELXMASS": {
                "name": "RELXMASS",
                "dimensions": ["numspec", "numpoint"],
                "shape": [2, 1],
                "ncattrs": {"long_name": "total release particle mass"},
            },
            "LAGE": {
                "name": "LAGE",
                "dimensions": ["nageclass"],
                "shape": [1],
                "ncattrs": {"units": "seconds", "long_name": "age class"},
            },
            "spec001": {
                "name": "spec001",
                "dimensions": [
                    "nageclass",
                    "numpoint",
                    "time",
                    "level",
                    "rlat",
                    "rlon",
                ],
                "shape": [1, 1, 11, 3, 30, 50],
                "ncattrs": {
                    "units": "ng kg-1",
                    "long_name": "Cs-137",
                    "coordinates": "lon lat",
                    "decay": 7.3265155e-10,
                    "weightmolar": -9.99,
                    "ohreact": -9.9e-09,
                    "vsetaver": -0.0003866022,
                    "spec_ass": -9,
                },
            },
            "WD_spec001": {
                "name": "WD_spec001",
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 50],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "Cs-137_wet_deposition",
                    "coordinates": "lon lat",
                    "weta": 7e-05,
                    "wetb": 0.8,
                    "dquer": 0.6,
                    "henry": 0.0,
                },
            },
            "DD_spec001": {
                "name": "DD_spec001",
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 50],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "Cs-137_dry_deposition",
                    "coordinates": "lon lat",
                    "dryvel": 0.0015,
                    "reldiff": -9.9,
                    "henry": 0.0,
                    "f0": 0.0,
                    "dquer": 0.6,
                    "density": 2500.0,
                    "dsigma": 0.3,
                },
            },
            "spec002": {
                "name": "spec002",
                "dimensions": [
                    "nageclass",
                    "numpoint",
                    "time",
                    "level",
                    "rlat",
                    "rlon",
                ],
                "shape": [1, 1, 11, 3, 30, 50],
                "ncattrs": {
                    "units": "ng kg-1",
                    "long_name": "I-131a",
                    "coordinates": "lon lat",
                    "decay": 9.978277e-07,
                    "weightmolar": -9.99,
                    "ohreact": -9.9e-09,
                    "vsetaver": -0.0003866022,
                    "spec_ass": -9,
                },
            },
            "WD_spec002": {
                "name": "WD_spec002",
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 50],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "I-131a_wet_deposition",
                    "coordinates": "lon lat",
                    "weta": 7e-05,
                    "wetb": 0.8,
                    "dquer": 0.6,
                    "henry": 0.0,
                },
            },
            "DD_spec002": {
                "name": "DD_spec002",
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 50],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "I-131a_dry_deposition",
                    "coordinates": "lon lat",
                    "dryvel": 0.0015,
                    "reldiff": -9.9,
                    "henry": 0.0,
                    "f0": 0.0,
                    "dquer": 0.6,
                    "density": 2500.0,
                    "dsigma": 0.3,
                },
            },
            "fptot": {
                "name": "fptot",
                "dimensions": ["numpoint", "rlat", "rlon"],
                "shape": [1, 30, 50],
                "ncattrs": {
                    "coordinates": "lon lat",
                    "units": "ng kg-1",
                    "long_name": "total_footprint",
                    "sampling_height": "undefined",
                },
            },
        },
        "analysis": {"model": "cosmo2", "rotated_pole": True, "species_ids": [1, 2]},
    },
    "fld": {
        "dtype": "float32",
        "shape": [30, 50],
        "nanmin": 0.0,
        "nanmean": 0.13665476,
        "nanmedian": 0.0005988658,
        "nanmax": 13.303647,
        "nanmin_nonzero": 2.6811893e-11,
        "nanmean_nonzero": 0.17747374,
        "nanmedian_nonzero": 0.0023225571,
        "nanmax_nonzero": 13.303647,
        "n_nan": 0,
        "n_zero": 345,
    },
    "lat": {"dtype": "float32", "shape": [30], "min": -3.3199997, "max": -0.42000008},
    "lon": {"dtype": "float32", "shape": [50], "min": -2.42, "max": 2.4799995},
}

plot_summary = {
    "type": "Plot",
    "ax_map": {"type": "MapAxesRotatedPole"},
    "boxes": {
        "method:Plot.fill_box_top_left": {
            "type": "TextBoxAxes",
            "name": "top/left",
            "rect": [0.0, 0.9, 0.7872, 0.1],
            "lw_frame": 1.0,
            "dx_unit": 0.009527439024390244,
            "dy_unit": 0.09000000000000001,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.09000000000000001,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.009527439024390244,
                        "y0": 0.91,
                        "x": 0.009527439024390244,
                        "y": 0.91,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Ensemble mean of total surface deposition of Cs-137 + I-131a",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "large", "ha": "left", "va": "top"},
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.09000000000000001,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.009527439024390244,
                        "y0": 0.09000000000000001,
                        "x": 0.009527439024390244,
                        "y": 0.09000000000000001,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Accumulated over 33:00$\\,$h since +0:00$\\,$h",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "large", "ha": "left", "va": "baseline"},
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.09000000000000001,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.9904725609756098,
                        "y0": 0.91,
                        "x": 0.9904725609756098,
                        "y": 0.91,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "2019-07-28 21:00 UTC (+33:00$\\,$h)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "large", "ha": "right", "va": "top"},
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.09000000000000001,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.9904725609756098,
                        "y0": 0.09000000000000001,
                        "x": 0.9904725609756098,
                        "y": 0.09000000000000001,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": '33:00$\\,$h since release start at G$\\mathrm{\\"o}$sgen',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "large", "ha": "right", "va": "baseline"},
                },
            ],
        },
        "method:Plot.fill_box_top_right": {
            "type": "TextBoxAxes",
            "name": "top/right",
            "rect": [0.8, 0.9, 0.2, 0.1],
            "lw_frame": 1.0,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.09000000000000001,
            "elements": {},
        },
        "method:Plot.fill_box_right_top": {
            "type": "TextBoxAxes",
            "name": "right/top",
            "rect": [0.8, 0.52, 0.2, 0.36],
            "lw_frame": 1.0,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.024999999999999998,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": 0.0,
                        "dy": 1.5,
                        "x0": 0.5,
                        "y0": 0.975,
                        "x": 0.5,
                        "y": 1.0125,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Deposition (Bq h m$^{-2}$)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "large", "ha": "center", "va": "top"},
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 7.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.21249999999999997,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "1E-07 $\\tt -$ 1E-06",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 10.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.2875,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "1E-06 $\\tt -$ 1E-05",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 13.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.3625,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "1E-05 $\\tt -$ 1E-04",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 16.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.4375,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "1E-04 $\\tt -$ 0.001",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 19.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.5125,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "0.001 $\\tt -$ 0.01 ",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 22.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.5875,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": " 0.01 $\\tt -$ 0.1  ",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 25.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.6625,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "  0.1 $\\tt -$ 1.0  ",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 28.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.7374999999999999,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "  1.0 $\\tt -$ 10.0 ",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 31.5,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.8125,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "      $\\tt \\geq$ 10.0 ",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "medium",
                        "family": "monospace",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 7.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.20249999999999996,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "bisque",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 10.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.27749999999999997,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "violet",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 13.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.3525,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "rebeccapurple",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 16.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.42750000000000005,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "cornflowerblue",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 19.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.5025,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "forestgreen",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 22.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.5775,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "yellowgreen",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 25.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.6525,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "greenyellow",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 28.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.7275,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "yellow",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -10,
                        "dy": 31.1,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.12499999999999994,
                        "y": 0.8025,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "lightgray",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementMarker",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -8.0,
                        "dy": 0.95,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.19999999999999996,
                        "y": 0.048749999999999995,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "m": "^",
                    "kwargs": {
                        "markeredgecolor": "red",
                        "markerfacecolor": "white",
                        "markersize": 7.5,
                        "markeredgewidth": 1.5,
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 0.25,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.031249999999999997,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "Release site",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                },
                {
                    "type": "TextBoxElementMarker",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -8.0,
                        "dy": 3.95,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.19999999999999996,
                        "y": 0.12374999999999999,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "m": "+",
                    "kwargs": {
                        "color": "black",
                        "markersize": 10,
                        "markeredgewidth": 1.5,
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bc",
                        "loc_y": "b",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.024999999999999998,
                        "dx": -3,
                        "dy": 3.25,
                        "x0": 0.5,
                        "y0": 0.024999999999999998,
                        "x": 0.38749999999999996,
                        "y": 0.10624999999999998,
                        "va": "baseline",
                        "ha": "center",
                    },
                    "s": "Max.: 13.3",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                },
            ],
        },
        "method:Plot.fill_box_right_bottom": {
            "type": "TextBoxAxes",
            "name": "right/bottom",
            "rect": [0.8, 0.05, 0.2, 0.45],
            "lw_frame": 1.0,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.019999999999999997,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": -1.0,
                        "x0": 0.5,
                        "y0": 0.98,
                        "x": 0.5,
                        "y": 0.96,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Release",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "large", "ha": "center", "va": "top"},
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 1.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.04999999999999999,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Washout exponent:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 4.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.09999999999999998,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Washout coeff.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 6.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.14999999999999997,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Sediment. vel.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 9.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.19999999999999996,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Deposit. vel.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 11.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.24999999999999994,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Half-life:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 14.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.3,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Substance:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 19.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.39999999999999997,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Total mass:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 21.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.44999999999999996,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Rate:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 24.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.49999999999999994,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "End:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 26.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.5499999999999999,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Start:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 31.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.6499999999999999,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Height:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 34.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.7,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Longitude:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 36.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.7499999999999999,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Latitude:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 39.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.019999999999999997,
                        "x": 0.037500000000000006,
                        "y": 0.7999999999999999,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Site:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 1.5,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.04999999999999999,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "0.8",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 4.0,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.09999999999999998,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "7e-05$\\,$s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 6.5,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.14999999999999997,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "0$\\,$m s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 9.0,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.19999999999999996,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "0.0015$\\,$m s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 11.5,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.24999999999999994,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "30$\\,$a / 8$\\,$d",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 14.0,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.3,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "Cs-137 / I-131a",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 19.0,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.39999999999999997,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "1e+09$\\,$Bq",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 21.5,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.44999999999999996,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "34722.2$\\,$Bq s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 24.0,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.49999999999999994,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "2019-07-27 20:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 26.5,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.5499999999999999,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "2019-07-27 12:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 31.5,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.6499999999999999,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "100$\\,$m AGL",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 34.0,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.7,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "7$^\\circ$$\\,$58'$\\,$E (7.9700$^\\circ$$\\,$E)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 36.5,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.7499999999999999,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": "47$^\\circ$$\\,$22'$\\,$N (47.3700$^\\circ$$\\,$N)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.019999999999999997,
                        "dx": 0.0,
                        "dy": 39.0,
                        "x0": 0.9625,
                        "y0": 0.019999999999999997,
                        "x": 0.9625,
                        "y": 0.7999999999999999,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": 'G$\\mathrm{\\"o}$sgen',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "size": "small",
                        "ha": "right",
                        "va": "baseline",
                    },
                },
            ],
        },
        "method:Plot.fill_box_bottom": {
            "type": "TextBoxAxes",
            "name": "bottom",
            "rect": [0.0, 0.0, 1.0, 0.05],
            "lw_frame": None,
            "dx_unit": 0.0075,
            "dy_unit": 0.17999999999999997,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.0075,
                        "dy_unit": 0.17999999999999997,
                        "dx": -0.7,
                        "dy": 0.5,
                        "x0": 0.0075,
                        "y0": 0.8200000000000001,
                        "x": 0.0022500000000000003,
                        "y": 0.91,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "FLEXPART based on COSMO-2 ensemble (X members: XX-YY), 2019-07-27 12:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "small", "ha": "left", "va": "top"},
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.0075,
                        "dy_unit": 0.17999999999999997,
                        "dx": 0.7,
                        "dy": 0.5,
                        "x0": 0.9925,
                        "y0": 0.8200000000000001,
                        "x": 0.99775,
                        "y": 0.91,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "©MeteoSwiss",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"size": "small", "ha": "right", "va": "top"},
                },
            ],
        },
    },
    "field": {
        "type": "Field",
        "rotated_pole": True,
        "var_setups": [
            {
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "outfile": "plot.png",
                "plot_type": "ens_mean",
                "variable": "deposition",
                "deposition_type": "dry",
                "integrate": True,
                "combine_species": True,
                "simulation_type": "ensemble",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "lang": "en",
                "domain": "auto",
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "species_id": [1],
                "time": [10],
                "level": None,
            },
            {
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "outfile": "plot.png",
                "plot_type": "ens_mean",
                "variable": "deposition",
                "deposition_type": "dry",
                "integrate": True,
                "combine_species": True,
                "simulation_type": "ensemble",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "lang": "en",
                "domain": "auto",
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "species_id": [2],
                "time": [10],
                "level": None,
            },
            {
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "outfile": "plot.png",
                "plot_type": "ens_mean",
                "variable": "deposition",
                "deposition_type": "wet",
                "integrate": True,
                "combine_species": True,
                "simulation_type": "ensemble",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "lang": "en",
                "domain": "auto",
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "species_id": [1],
                "time": [10],
                "level": None,
            },
            {
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "outfile": "plot.png",
                "plot_type": "ens_mean",
                "variable": "deposition",
                "deposition_type": "wet",
                "integrate": True,
                "combine_species": True,
                "simulation_type": "ensemble",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "lang": "en",
                "domain": "auto",
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "species_id": [2],
                "time": [10],
                "level": None,
            },
        ],
        "time_stats": {
            "mean": 0.06554155,
            "median": 0.0,
            "mean_nz": 0.29628372,
            "median_nz": 0.0031997827,
            "max": 13.710873,
        },
        "nc_meta_data": {
            "ncattrs": {"dxout": 0.02, "dyout": 0.02},
            "dimensions": {
                "time": {"name": "time", "size": 11},
                "rlon": {"name": "rlon", "size": 50},
                "rlat": {"name": "rlat", "size": 30},
                "level": {"name": "level", "size": 3},
                "numspec": {"name": "numspec", "size": 2},
                "numpoint": {"name": "numpoint", "size": 1},
                "nageclass": {"name": "nageclass", "size": 1},
                "nchar": {"name": "nchar", "size": 45},
            },
            "variables": {
                "time": {
                    "name": "time",
                    "dimensions": ["time"],
                    "shape": [11],
                    "ncattrs": {
                        "units": "seconds since 2019-07-27 12:00",
                        "calendar": "proleptic_gregorian",
                    },
                },
                "rlon": {
                    "name": "rlon",
                    "dimensions": ["rlon"],
                    "shape": [50],
                    "ncattrs": {
                        "long_name": "longitude in rotated pole grid",
                        "units": "degrees",
                        "standard_name": "grid_longitude",
                        "axis": "X",
                        "description": "grid cell centers",
                    },
                },
                "rlat": {
                    "name": "rlat",
                    "dimensions": ["rlat"],
                    "shape": [30],
                    "ncattrs": {
                        "long_name": "latitude in rotated pole grid",
                        "units": "degrees",
                        "standard_name": "grid_latitude",
                        "axis": "Y",
                        "description": "grid cell centers",
                    },
                },
                "level": {
                    "name": "level",
                    "dimensions": ["level"],
                    "shape": [3],
                    "ncattrs": {
                        "axis": "Z",
                        "units": "meters",
                        "positive": "up",
                        "standard_name": "height",
                        "long_name": "height above ground",
                        "description": "grid cell top",
                    },
                },
                "rotated_pole": {
                    "name": "rotated_pole",
                    "dimensions": {},
                    "shape": {},
                    "ncattrs": {
                        "grid_mapping_name": "rotated_latitude_longitude",
                        "grid_north_pole_latitude": 43.0,
                        "grid_north_pole_longitude": -170.0,
                    },
                },
                "RELCOM": {
                    "name": "RELCOM",
                    "dimensions": ["numpoint", "nchar"],
                    "shape": [1, 45],
                    "ncattrs": {"long_name": "release point name"},
                },
                "RELLNG1": {
                    "name": "RELLNG1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_east",
                        "long_name": "release longitude lower left corner",
                    },
                },
                "RELLNG2": {
                    "name": "RELLNG2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_east",
                        "long_name": "release longitude upper right corner",
                    },
                },
                "RELLAT1": {
                    "name": "RELLAT1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_north",
                        "long_name": "release latitude lower left corner",
                    },
                },
                "RELLAT2": {
                    "name": "RELLAT2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_north",
                        "long_name": "release latitude upper right corner",
                    },
                },
                "RELZZ1": {
                    "name": "RELZZ1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "meters",
                        "long_name": "release height bottom",
                    },
                },
                "RELZZ2": {
                    "name": "RELZZ2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"units": "meters", "long_name": "release height top"},
                },
                "RELKINDZ": {
                    "name": "RELKINDZ",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"long_name": "release kind"},
                },
                "RELSTART": {
                    "name": "RELSTART",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "seconds",
                        "long_name": "release start relative to simulation start",
                    },
                },
                "RELEND": {
                    "name": "RELEND",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "seconds",
                        "long_name": "release end relative to simulation start",
                    },
                },
                "RELPART": {
                    "name": "RELPART",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"long_name": "number of release particles"},
                },
                "RELXMASS": {
                    "name": "RELXMASS",
                    "dimensions": ["numspec", "numpoint"],
                    "shape": [2, 1],
                    "ncattrs": {"long_name": "total release particle mass"},
                },
                "LAGE": {
                    "name": "LAGE",
                    "dimensions": ["nageclass"],
                    "shape": [1],
                    "ncattrs": {"units": "seconds", "long_name": "age class"},
                },
                "spec001": {
                    "name": "spec001",
                    "dimensions": [
                        "nageclass",
                        "numpoint",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "shape": [1, 1, 11, 3, 30, 50],
                    "ncattrs": {
                        "units": "ng kg-1",
                        "long_name": "Cs-137",
                        "coordinates": "lon lat",
                        "decay": 7.3265155e-10,
                        "weightmolar": -9.99,
                        "ohreact": -9.9e-09,
                        "vsetaver": -0.0003866022,
                        "spec_ass": -9,
                    },
                },
                "WD_spec001": {
                    "name": "WD_spec001",
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 50],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "Cs-137_wet_deposition",
                        "coordinates": "lon lat",
                        "weta": 7e-05,
                        "wetb": 0.8,
                        "dquer": 0.6,
                        "henry": 0.0,
                    },
                },
                "DD_spec001": {
                    "name": "DD_spec001",
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 50],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "Cs-137_dry_deposition",
                        "coordinates": "lon lat",
                        "dryvel": 0.0015,
                        "reldiff": -9.9,
                        "henry": 0.0,
                        "f0": 0.0,
                        "dquer": 0.6,
                        "density": 2500.0,
                        "dsigma": 0.3,
                    },
                },
                "spec002": {
                    "name": "spec002",
                    "dimensions": [
                        "nageclass",
                        "numpoint",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "shape": [1, 1, 11, 3, 30, 50],
                    "ncattrs": {
                        "units": "ng kg-1",
                        "long_name": "I-131a",
                        "coordinates": "lon lat",
                        "decay": 9.978277e-07,
                        "weightmolar": -9.99,
                        "ohreact": -9.9e-09,
                        "vsetaver": -0.0003866022,
                        "spec_ass": -9,
                    },
                },
                "WD_spec002": {
                    "name": "WD_spec002",
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 50],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "I-131a_wet_deposition",
                        "coordinates": "lon lat",
                        "weta": 7e-05,
                        "wetb": 0.8,
                        "dquer": 0.6,
                        "henry": 0.0,
                    },
                },
                "DD_spec002": {
                    "name": "DD_spec002",
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 50],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "I-131a_dry_deposition",
                        "coordinates": "lon lat",
                        "dryvel": 0.0015,
                        "reldiff": -9.9,
                        "henry": 0.0,
                        "f0": 0.0,
                        "dquer": 0.6,
                        "density": 2500.0,
                        "dsigma": 0.3,
                    },
                },
                "fptot": {
                    "name": "fptot",
                    "dimensions": ["numpoint", "rlat", "rlon"],
                    "shape": [1, 30, 50],
                    "ncattrs": {
                        "coordinates": "lon lat",
                        "units": "ng kg-1",
                        "long_name": "total_footprint",
                        "sampling_height": "undefined",
                    },
                },
            },
            "analysis": {
                "model": "cosmo2",
                "rotated_pole": True,
                "species_ids": [1, 2],
            },
        },
        "fld": {
            "dtype": "float32",
            "shape": [30, 50],
            "nanmin": 0.0,
            "nanmean": 0.13665476,
            "nanmedian": 0.0005988658,
            "nanmax": 13.303647,
            "nanmin_nonzero": 2.6811893e-11,
            "nanmean_nonzero": 0.17747374,
            "nanmedian_nonzero": 0.0023225571,
            "nanmax_nonzero": 13.303647,
            "n_nan": 0,
            "n_zero": 345,
        },
        "lat": {
            "dtype": "float32",
            "shape": [30],
            "min": -3.3199997,
            "max": -0.42000008,
        },
        "lon": {"dtype": "float32", "shape": [50], "min": -2.42, "max": 2.4799995},
    },
    "fig": {
        "type": "Figure",
        "axes": [
            {
                "type": "GeoAxes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (0.0, 40.0, 984.0, 664.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (0.0, 720.0, 984.0, 80.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 720.0, 250.0, 80.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 416.0, 250.0, 288.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 40.0, 250.0, 360.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {"type": "TransformedBbox", "bounds": (0.0, 0.0, 1250.0, 40.0)},
            },
        ],
        "bbox": {"type": "TransformedBbox", "bounds": (0.0, 0.0, 1250.0, 800.0)},
    },
    "map_conf": {
        "type": "MapAxesConf",
        "geo_res": "10m",
        "geo_res_cities": "50m",
        "geo_res_rivers": "50m",
        "lang": "en",
        "lllat": None,
        "lllon": None,
        "lw_frame": 1.0,
        "min_city_pop": 300000,
        "urlat": None,
        "urlon": None,
        "ref_dist_conf": {
            "type": "RefDistIndConf",
            "dist": 100,
            "pos": "bl",
            "unit": "km",
        },
        "ref_dist_on": True,
        "rel_offset": [0.0, 0.0],
        "zoom_fact": 1.02,
    },
}
