# -*- coding: utf-8 -*-
"""
Test reference for pytest test.

tests/slow/pyflexplot/test_plots/shared.py
    ::Test_IntegratedConcentration
    ::test

Created by temporarily changing the parent class of
``Test_IntegratedConcentration``
from ``_TestBase`` to ``_CreateReference`` and running pytest.
"""

field_summary = {
    "fld": {
        "dtype": "float32",
        "n_nan": 0,
        "n_zero": 501,
        "nanmax": 0.038744926,
        "nanmax_nonzero": 0.038744926,
        "nanmean": 9.845621e-05,
        "nanmean_nonzero": 0.00016902352,
        "nanmedian": 6.9165535e-06,
        "nanmedian_nonzero": 3.9854775e-05,
        "nanmin": 0.0,
        "nanmin_nonzero": 5.969089e-10,
        "shape": (30, 40),
    },
    "lat": {"dtype": "float32", "max": 2.9499998, "min": -1.4000003, "shape": (30,)},
    "lon": {"dtype": "float32", "max": 4.0499997, "min": -1.7999997, "shape": (40,)},
    "nc_meta_data": {
        "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
        "dimensions": {
            "level": {"name": "level", "size": 3},
            "nageclass": {"name": "nageclass", "size": 1},
            "nchar": {"name": "nchar", "size": 45},
            "noutrel": {"name": "noutrel", "size": 1},
            "numpoint": {"name": "numpoint", "size": 1},
            "numspec": {"name": "numspec", "size": 1},
            "rlat": {"name": "rlat", "size": 30},
            "rlon": {"name": "rlon", "size": 40},
            "time": {"name": "time", "size": 11},
        },
        "ncattrs": {"dxout": 0.01, "dyout": 0.01},
        "variables": {
            "DD_spec001": {
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "name": "DD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "density": 2500.0,
                    "dquer": 0.6,
                    "dryvel": 0.0015,
                    "dsigma": 0.3,
                    "f0": 0.0,
                    "henry": 0.0,
                    "long_name": "Cs-137_dry_deposition",
                    "reldiff": -9.9,
                    "units": "1e-12 kg " "m-2",
                },
                "shape": [1, 1, 11, 30, 40],
            },
            "LAGE": {
                "dimensions": ["nageclass"],
                "name": "LAGE",
                "ncattrs": {"long_name": "age class", "units": "seconds"},
                "shape": [1],
            },
            "RELCOM": {
                "dimensions": ["numpoint", "nchar"],
                "name": "RELCOM",
                "ncattrs": {"long_name": "release " "point " "name"},
                "shape": [1, 45],
            },
            "RELEND": {
                "dimensions": ["numpoint"],
                "name": "RELEND",
                "ncattrs": {
                    "long_name": "release "
                    "end "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELKINDZ": {
                "dimensions": ["numpoint"],
                "name": "RELKINDZ",
                "ncattrs": {"long_name": "release " "kind"},
                "shape": [1],
            },
            "RELLAT1": {
                "dimensions": ["numpoint"],
                "name": "RELLAT1",
                "ncattrs": {
                    "long_name": "release " "latitude " "lower " "left " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLAT2": {
                "dimensions": ["numpoint"],
                "name": "RELLAT2",
                "ncattrs": {
                    "long_name": "release " "latitude " "upper " "right " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLNG1": {
                "dimensions": ["numpoint"],
                "name": "RELLNG1",
                "ncattrs": {
                    "long_name": "release " "longitude " "lower " "left " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELLNG2": {
                "dimensions": ["numpoint"],
                "name": "RELLNG2",
                "ncattrs": {
                    "long_name": "release " "longitude " "upper " "right " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELPART": {
                "dimensions": ["numpoint"],
                "name": "RELPART",
                "ncattrs": {"long_name": "number " "of " "release " "particles"},
                "shape": [1],
            },
            "RELSTART": {
                "dimensions": ["numpoint"],
                "name": "RELSTART",
                "ncattrs": {
                    "long_name": "release "
                    "start "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELXMASS": {
                "dimensions": ["numspec", "numpoint"],
                "name": "RELXMASS",
                "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                "shape": [1, 1],
            },
            "RELZZ1": {
                "dimensions": ["numpoint"],
                "name": "RELZZ1",
                "ncattrs": {
                    "long_name": "release " "height " "bottom",
                    "units": "meters",
                },
                "shape": [1],
            },
            "RELZZ2": {
                "dimensions": ["numpoint"],
                "name": "RELZZ2",
                "ncattrs": {"long_name": "release " "height " "top", "units": "meters"},
                "shape": [1],
            },
            "WD_spec001": {
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "name": "WD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "dquer": 0.6,
                    "henry": 0.0,
                    "long_name": "Cs-137_wet_deposition",
                    "units": "1e-12 kg " "m-2",
                    "weta": 7e-05,
                    "wetb": 0.8,
                },
                "shape": [1, 1, 11, 30, 40],
            },
            "fptot": {
                "dimensions": ["noutrel", "rlat", "rlon"],
                "name": "fptot",
                "ncattrs": {
                    "coordinates": "lon lat",
                    "long_name": "total_footprint",
                    "sampling_height": "undefined",
                    "units": "ng kg-1",
                },
                "shape": [1, 30, 40],
            },
            "level": {
                "dimensions": ["level"],
                "name": "level",
                "ncattrs": {
                    "axis": "Z",
                    "description": "grid " "cell top",
                    "long_name": "height " "above " "ground",
                    "positive": "up",
                    "standard_name": "height",
                    "units": "meters",
                },
                "shape": [3],
            },
            "rlat": {
                "dimensions": ["rlat"],
                "name": "rlat",
                "ncattrs": {
                    "axis": "Y",
                    "description": "grid cell " "centers",
                    "long_name": "latitude in " "rotated " "pole grid",
                    "standard_name": "grid_latitude",
                    "units": "degrees",
                },
                "shape": [30],
            },
            "rlon": {
                "dimensions": ["rlon"],
                "name": "rlon",
                "ncattrs": {
                    "axis": "X",
                    "description": "grid cell " "centers",
                    "long_name": "longitude " "in rotated " "pole grid",
                    "standard_name": "grid_longitude",
                    "units": "degrees",
                },
                "shape": [40],
            },
            "rotated_pole": {
                "dimensions": {},
                "name": "rotated_pole",
                "ncattrs": {
                    "grid_mapping_name": "rotated_latitude_longitude",
                    "grid_north_pole_latitude": 43.0,
                    "grid_north_pole_longitude": -170.0,
                },
                "shape": {},
            },
            "spec001": {
                "dimensions": ["nageclass", "noutrel", "time", "level", "rlat", "rlon"],
                "name": "spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "decay": 7.3265155e-10,
                    "long_name": "Cs-137",
                    "ohreact": -9.9e-09,
                    "spec_ass": -9,
                    "units": "ng kg-1",
                    "vsetaver": -0.0003866022,
                    "weightmolar": -9.99,
                },
                "shape": [1, 1, 11, 3, 30, 40],
            },
            "time": {
                "dimensions": ["time"],
                "name": "time",
                "ncattrs": {
                    "calendar": "proleptic_gregorian",
                    "units": "seconds since " "2019-09-30 " "12:00",
                },
                "shape": [11],
            },
        },
    },
    "rotated_pole": True,
    "time_stats": {
        "max": 0.038744926,
        "mean": 6.225337e-05,
        "mean_nz": 0.00016808025,
        "median": 0.0,
        "median_nz": 2.5472184e-05,
    },
    "type": "Field",
    "var_setups": [
        {
            "combine_species": False,
            "deposition_type": "none",
            "domain": "ch",
            "ens_member_id": None,
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "infile": "flexpart_cosmo-1_2019093012.nc",
            "integrate": True,
            "lang": "de",
            "level": [0],
            "nageclass": [0],
            "noutrel": [0],
            "numpoint": [0],
            "outfile": "plot.png",
            "plot_type": "auto",
            "simulation_type": "deterministic",
            "species_id": [1],
            "time": [10],
            "variable": "concentration",
        }
    ],
}

plot_summary = {
    "ax_map": {"type": "MapAxesRotatedPole"},
    "boxes": {
        "method:Plot.fill_box_bottom": {
            "dx_unit": 0.0075,
            "dy_unit": 0.17999999999999997,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "small", "va": "top"},
                    "loc": {
                        "dx": -0.7,
                        "dx_unit": 0.0075,
                        "dy": 0.5,
                        "dy_unit": 0.17999999999999997,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.0022500000000000003,
                        "x0": 0.0075,
                        "y": 0.91,
                        "y0": 0.8200000000000001,
                    },
                    "replace_edge_spaces": False,
                    "s": "FLEXPART "
                    "basierend auf "
                    "COSMO-1, "
                    "2019-09-30 "
                    "12:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "small", "va": "top"},
                    "loc": {
                        "dx": 0.7,
                        "dx_unit": 0.0075,
                        "dy": 0.5,
                        "dy_unit": 0.17999999999999997,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.99775,
                        "x0": 0.9925,
                        "y": 0.91,
                        "y0": 0.8200000000000001,
                    },
                    "replace_edge_spaces": False,
                    "s": "©MeteoSchweiz",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": None,
            "name": "bottom",
            "rect": [0.0, 0.0, 1.0, 0.05],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_bottom": {
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.019999999999999997,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": -1.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.96,
                        "y0": 0.98,
                    },
                    "replace_edge_spaces": False,
                    "s": "Freisetzung",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 1.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.04999999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschexponent:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 4.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.09999999999999998,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschkoeff.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 6.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.14999999999999997,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Sediment.-Geschw.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 9.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.19999999999999996,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Deposit.-Geschw.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 11.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.24999999999999994,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Halbwertszeit:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 14.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.3,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Substanz:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 19.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.39999999999999997,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Totale " "Masse:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 21.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.44999999999999996,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Rate:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 24.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.49999999999999994,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ende:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 26.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.5499999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Start:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 31.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.6499999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": 'H$\\mathrm{\\"o}$he:',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 34.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.7,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": 'L$\\mathrm{\\"a}$nge:',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 36.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.7499999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Breite:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 39.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.037500000000000006,
                        "x0": 0.037500000000000006,
                        "y": 0.7999999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 1.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.04999999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "0.8",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 4.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.09999999999999998,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "7e-05$\\,$s$^{-1}$",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 6.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.14999999999999997,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "0$\\,$m " "s$^{-1}$",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 9.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.19999999999999996,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "0.0015$\\,$m " "s$^{-1}$",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 11.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.24999999999999994,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "30.17$\\,$a",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 14.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.3,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 19.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.39999999999999997,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "1e+09$\\,$Bq",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 21.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.44999999999999996,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "34722.2$\\,$Bq " "s$^{-1}$",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 24.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.49999999999999994,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-09-30 " "20:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 26.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.5499999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-09-30 " "12:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 31.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.6499999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "100$\\,$m " '$\\mathrm{\\"u}$.G.',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 34.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.7,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "7$^\\circ$$\\,$58'$\\,$O " "(7.9668$^\\circ$$\\,$O)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 36.5,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.7499999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": "47$^\\circ$$\\,$21'$\\,$N " "(47.3659$^\\circ$$\\,$N)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 39.0,
                        "dy_unit": 0.019999999999999997,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9625,
                        "x0": 0.9625,
                        "y": 0.7999999999999999,
                        "y0": 0.019999999999999997,
                    },
                    "replace_edge_spaces": False,
                    "s": 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/bottom",
            "rect": [0.8, 0.05, 0.2, 0.45],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_top": {
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.024999999999999998,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 1.5,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 1.0125,
                        "y0": 0.975,
                    },
                    "replace_edge_spaces": False,
                    "s": "Int. " "Konzentr. " "(Bq h " "m$^{-3}$)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 9.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.24999999999999997,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-09 $\\tt " "-$ 1E-08",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 12.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.325,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-08 $\\tt " "-$ 1E-07",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 15.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.39999999999999997,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-07 $\\tt " "-$ 1E-06",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 18.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.475,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-06 $\\tt " "-$ 1E-05",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 21.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.5499999999999999,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-05 $\\tt " "-$ 1E-04",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 24.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.625,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-04 $\\tt " "-$ 0.001",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 27.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.7,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "0.001 $\\tt " "-$ 0.01 ",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 30.0,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.7749999999999999,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "      $\\tt " "\\geq$ 0.01 ",
                    "type": "TextBoxElementText",
                },
                {
                    "ec": "black",
                    "fc": [0.8784313725490196, 0.7686274509803922, 0.6745098039215687],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 8.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.23999999999999996,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.8666666666666667, 0.4980392156862745, 0.8431372549019608],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 11.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.315,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.38823529411764707, 0.0, 1.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 14.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.38999999999999996,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.39215686274509803, 0.6, 0.7803921568627451],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 17.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.465,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.36470588235294116, 1.0, 0.00784313725490196],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 20.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.54,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7803921568627451, 1.0, 0.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 23.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.615,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [1.0, 0.9372549019607843, 0.2235294117647059],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 26.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.6900000000000001,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7843137254901961, 0.7843137254901961, 0.7843137254901961],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.037500000000000006,
                        "dy": 29.6,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.12499999999999994,
                        "x0": 0.5,
                        "y": 0.765,
                        "y0": 0.024999999999999998,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "kwargs": {
                        "markeredgecolor": "red",
                        "markeredgewidth": 1.5,
                        "markerfacecolor": "white",
                        "markersize": 7.5,
                    },
                    "loc": {
                        "dx": -8.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 0.95,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.19999999999999996,
                        "x0": 0.5,
                        "y": 0.048749999999999995,
                        "y0": 0.024999999999999998,
                    },
                    "m": "^",
                    "type": "TextBoxElementMarker",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 0.25,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.031249999999999997,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "Abgabeort",
                    "type": "TextBoxElementText",
                },
                {
                    "kwargs": {
                        "color": "black",
                        "markeredgewidth": 1.5,
                        "markersize": 10,
                    },
                    "loc": {
                        "dx": -8.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 3.95,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.19999999999999996,
                        "x0": 0.5,
                        "y": 0.12374999999999999,
                        "y0": 0.024999999999999998,
                    },
                    "m": "+",
                    "type": "TextBoxElementMarker",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.037500000000000006,
                        "dy": 3.25,
                        "dy_unit": 0.024999999999999998,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.38749999999999996,
                        "x0": 0.5,
                        "y": 0.10624999999999998,
                        "y0": 0.024999999999999998,
                    },
                    "replace_edge_spaces": False,
                    "s": "Max.: 0.0387",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/top",
            "rect": [0.8, 0.52, 0.2, 0.36],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_left": {
            "dx_unit": 0.009527439024390244,
            "dy_unit": 0.09000000000000001,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.009527439024390244,
                        "dy": 0.0,
                        "dy_unit": 0.09000000000000001,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.009527439024390244,
                        "x0": 0.009527439024390244,
                        "y": 0.91,
                        "y0": 0.91,
                    },
                    "replace_edge_spaces": False,
                    "s": 'Aktivit$\\mathrm{\\"a}$tskonzentr. '
                    "auf 0$-$500 m "
                    '$\\mathrm{\\"u}$.G.',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.009527439024390244,
                        "dy": 0.0,
                        "dy_unit": 0.09000000000000001,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.009527439024390244,
                        "x0": 0.009527439024390244,
                        "y": 0.09000000000000001,
                        "y0": 0.09000000000000001,
                    },
                    "replace_edge_spaces": False,
                    "s": "Aufsummiert "
                    '$\\mathrm{\\"u}$ber '
                    "33$\\,$h "
                    "(seit "
                    "+00:00$\\,$h)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.009527439024390244,
                        "dy": 0.0,
                        "dy_unit": 0.09000000000000001,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.9904725609756098,
                        "x0": 0.9904725609756098,
                        "y": 0.91,
                        "y0": 0.91,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-10-01 " "21:00 UTC " "(+33:00$\\,$h)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.009527439024390244,
                        "dy": 0.0,
                        "dy_unit": 0.09000000000000001,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.9904725609756098,
                        "x0": 0.9904725609756098,
                        "y": 0.09000000000000001,
                        "y0": 0.09000000000000001,
                    },
                    "replace_edge_spaces": False,
                    "s": "33:00$\\,$h " "seit " "Freisetzungsbeginn",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/left",
            "rect": [0.0, 0.9, 0.7872, 0.1],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_right": {
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.09000000000000001,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 0.0,
                        "dy_unit": 0.09000000000000001,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.91,
                        "y0": 0.91,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.037500000000000006,
                        "dy": 0.0,
                        "dy_unit": 0.09000000000000001,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.09000000000000001,
                        "y0": 0.09000000000000001,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort: " 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/right",
            "rect": [0.8, 0.9, 0.2, 0.1],
            "type": "TextBoxAxes",
        },
    },
    "field": {
        "fld": {
            "dtype": "float32",
            "n_nan": 0,
            "n_zero": 501,
            "nanmax": 0.038744926,
            "nanmax_nonzero": 0.038744926,
            "nanmean": 9.845621e-05,
            "nanmean_nonzero": 0.00016902352,
            "nanmedian": 6.9165535e-06,
            "nanmedian_nonzero": 3.9854775e-05,
            "nanmin": 0.0,
            "nanmin_nonzero": 5.969089e-10,
            "shape": [30, 40],
        },
        "lat": {"dtype": "float32", "max": 2.9499998, "min": -1.4000003, "shape": [30]},
        "lon": {"dtype": "float32", "max": 4.0499997, "min": -1.7999997, "shape": [40]},
        "nc_meta_data": {
            "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
            "dimensions": {
                "level": {"name": "level", "size": 3},
                "nageclass": {"name": "nageclass", "size": 1},
                "nchar": {"name": "nchar", "size": 45},
                "noutrel": {"name": "noutrel", "size": 1},
                "numpoint": {"name": "numpoint", "size": 1},
                "numspec": {"name": "numspec", "size": 1},
                "rlat": {"name": "rlat", "size": 30},
                "rlon": {"name": "rlon", "size": 40},
                "time": {"name": "time", "size": 11},
            },
            "ncattrs": {"dxout": 0.01, "dyout": 0.01},
            "variables": {
                "DD_spec001": {
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "name": "DD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "density": 2500.0,
                        "dquer": 0.6,
                        "dryvel": 0.0015,
                        "dsigma": 0.3,
                        "f0": 0.0,
                        "henry": 0.0,
                        "long_name": "Cs-137_dry_deposition",
                        "reldiff": -9.9,
                        "units": "1e-12 " "kg " "m-2",
                    },
                    "shape": [1, 1, 11, 30, 40],
                },
                "LAGE": {
                    "dimensions": ["nageclass"],
                    "name": "LAGE",
                    "ncattrs": {"long_name": "age " "class", "units": "seconds"},
                    "shape": [1],
                },
                "RELCOM": {
                    "dimensions": ["numpoint", "nchar"],
                    "name": "RELCOM",
                    "ncattrs": {"long_name": "release " "point " "name"},
                    "shape": [1, 45],
                },
                "RELEND": {
                    "dimensions": ["numpoint"],
                    "name": "RELEND",
                    "ncattrs": {
                        "long_name": "release "
                        "end "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELKINDZ": {
                    "dimensions": ["numpoint"],
                    "name": "RELKINDZ",
                    "ncattrs": {"long_name": "release " "kind"},
                    "shape": [1],
                },
                "RELLAT1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT1",
                    "ncattrs": {
                        "long_name": "release " "latitude " "lower " "left " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLAT2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT2",
                    "ncattrs": {
                        "long_name": "release " "latitude " "upper " "right " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLNG1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG1",
                    "ncattrs": {
                        "long_name": "release " "longitude " "lower " "left " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELLNG2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG2",
                    "ncattrs": {
                        "long_name": "release " "longitude " "upper " "right " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELPART": {
                    "dimensions": ["numpoint"],
                    "name": "RELPART",
                    "ncattrs": {"long_name": "number " "of " "release " "particles"},
                    "shape": [1],
                },
                "RELSTART": {
                    "dimensions": ["numpoint"],
                    "name": "RELSTART",
                    "ncattrs": {
                        "long_name": "release "
                        "start "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELXMASS": {
                    "dimensions": ["numspec", "numpoint"],
                    "name": "RELXMASS",
                    "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                    "shape": [1, 1],
                },
                "RELZZ1": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ1",
                    "ncattrs": {
                        "long_name": "release " "height " "bottom",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "RELZZ2": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ2",
                    "ncattrs": {
                        "long_name": "release " "height " "top",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "WD_spec001": {
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "name": "WD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "dquer": 0.6,
                        "henry": 0.0,
                        "long_name": "Cs-137_wet_deposition",
                        "units": "1e-12 " "kg " "m-2",
                        "weta": 7e-05,
                        "wetb": 0.8,
                    },
                    "shape": [1, 1, 11, 30, 40],
                },
                "fptot": {
                    "dimensions": ["noutrel", "rlat", "rlon"],
                    "name": "fptot",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "long_name": "total_footprint",
                        "sampling_height": "undefined",
                        "units": "ng " "kg-1",
                    },
                    "shape": [1, 30, 40],
                },
                "level": {
                    "dimensions": ["level"],
                    "name": "level",
                    "ncattrs": {
                        "axis": "Z",
                        "description": "grid " "cell " "top",
                        "long_name": "height " "above " "ground",
                        "positive": "up",
                        "standard_name": "height",
                        "units": "meters",
                    },
                    "shape": [3],
                },
                "rlat": {
                    "dimensions": ["rlat"],
                    "name": "rlat",
                    "ncattrs": {
                        "axis": "Y",
                        "description": "grid " "cell " "centers",
                        "long_name": "latitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_latitude",
                        "units": "degrees",
                    },
                    "shape": [30],
                },
                "rlon": {
                    "dimensions": ["rlon"],
                    "name": "rlon",
                    "ncattrs": {
                        "axis": "X",
                        "description": "grid " "cell " "centers",
                        "long_name": "longitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_longitude",
                        "units": "degrees",
                    },
                    "shape": [40],
                },
                "rotated_pole": {
                    "dimensions": {},
                    "name": "rotated_pole",
                    "ncattrs": {
                        "grid_mapping_name": "rotated_latitude_longitude",
                        "grid_north_pole_latitude": 43.0,
                        "grid_north_pole_longitude": -170.0,
                    },
                    "shape": {},
                },
                "spec001": {
                    "dimensions": [
                        "nageclass",
                        "noutrel",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "name": "spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "decay": 7.3265155e-10,
                        "long_name": "Cs-137",
                        "ohreact": -9.9e-09,
                        "spec_ass": -9,
                        "units": "ng " "kg-1",
                        "vsetaver": -0.0003866022,
                        "weightmolar": -9.99,
                    },
                    "shape": [1, 1, 11, 3, 30, 40],
                },
                "time": {
                    "dimensions": ["time"],
                    "name": "time",
                    "ncattrs": {
                        "calendar": "proleptic_gregorian",
                        "units": "seconds " "since " "2019-09-30 " "12:00",
                    },
                    "shape": [11],
                },
            },
        },
        "rotated_pole": True,
        "time_stats": {
            "max": 0.038744926,
            "mean": 6.225337e-05,
            "mean_nz": 0.00016808025,
            "median": 0.0,
            "median_nz": 2.5472184e-05,
        },
        "type": "Field",
        "var_setups": [
            {
                "combine_species": False,
                "deposition_type": "none",
                "domain": "ch",
                "ens_member_id": None,
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "infile": "flexpart_cosmo-1_2019093012.nc",
                "integrate": True,
                "lang": "de",
                "level": [0],
                "nageclass": [0],
                "noutrel": [0],
                "numpoint": [0],
                "outfile": "plot.png",
                "plot_type": "auto",
                "simulation_type": "deterministic",
                "species_id": [1],
                "time": [10],
                "variable": "concentration",
            }
        ],
    },
    "fig": {
        "axes": [
            {
                "bbox": {
                    "bounds": (0.0, 40.0, 984.0, 664.0),
                    "type": "TransformedBbox",
                },
                "type": "GeoAxes",
            },
            {
                "bbox": {
                    "bounds": (0.0, 720.0, 984.0, 80.0),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1000.0, 720.0, 250.0, 80.0),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1000.0, 416.0, 250.0, 288.0),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1000.0, 40.0, 250.0, 360.0),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {"bounds": (0.0, 0.0, 1250.0, 40.0), "type": "TransformedBbox"},
                "type": "Axes",
            },
        ],
        "bbox": {"bounds": (0.0, 0.0, 1250.0, 800.0), "type": "TransformedBbox"},
        "type": "Figure",
    },
    "map_conf": {
        "geo_res": "10m",
        "geo_res_cities": "10m",
        "geo_res_rivers": "10m",
        "lang": "de",
        "lllat": None,
        "lllon": None,
        "lw_frame": 1.0,
        "min_city_pop": 0,
        "ref_dist_conf": {
            "dist": 25,
            "pos": "bl",
            "type": "RefDistIndConf",
            "unit": "km",
        },
        "ref_dist_on": True,
        "rel_offset": [-0.02, 0.045],
        "type": "MapAxesConf",
        "urlat": None,
        "urlon": None,
        "zoom_fact": 3.6,
    },
    "type": "Plot",
}
