# -*- coding: utf-8 -*-
"""
Reference for test_cosmo1_deterministic.py::Test_TotalDeposition.
"""
field_summary = {
    "fld": {
        "dtype": "float32",
        "n_nan": 0,
        "n_zero": 545,
        "nanmax": 0.15455633,
        "nanmax_nonzero": 0.15455633,
        "nanmean": 0.0008733995,
        "nanmean_nonzero": 0.0016001214,
        "nanmedian": 1.5417452e-05,
        "nanmedian_nonzero": 0.0003491032,
        "nanmin": 0.0,
        "nanmin_nonzero": 4.145933e-09,
        "shape": (30, 40),
    },
    "lat": {"dtype": "float32", "max": 2.9499998, "min": -1.4000003, "shape": (30,)},
    "lon": {"dtype": "float32", "max": 4.0499997, "min": -1.7999997, "shape": (40,)},
    "nc_meta_data": {
        "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
        "dimensions": {
            "level": {"name": "level", "size": 3},
            "nageclass": {"name": "nageclass", "size": 1},
            "nchar": {"name": "nchar", "size": 45},
            "noutrel": {"name": "noutrel", "size": 1},
            "numpoint": {"name": "numpoint", "size": 1},
            "numspec": {"name": "numspec", "size": 1},
            "rlat": {"name": "rlat", "size": 30},
            "rlon": {"name": "rlon", "size": 40},
            "time": {"name": "time", "size": 11},
        },
        "ncattrs": {"dxout": 0.01, "dyout": 0.01},
        "variables": {
            "DD_spec001": {
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "name": "DD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "density": 2500.0,
                    "dquer": 0.6,
                    "dryvel": 0.0015,
                    "dsigma": 0.3,
                    "f0": 0.0,
                    "henry": 0.0,
                    "long_name": "Cs-137_dry_deposition",
                    "reldiff": -9.9,
                    "units": "1e-12 kg " "m-2",
                },
                "shape": [1, 1, 11, 30, 40],
            },
            "LAGE": {
                "dimensions": ["nageclass"],
                "name": "LAGE",
                "ncattrs": {"long_name": "age class", "units": "seconds"},
                "shape": [1],
            },
            "RELCOM": {
                "dimensions": ["numpoint", "nchar"],
                "name": "RELCOM",
                "ncattrs": {"long_name": "release " "point " "name"},
                "shape": [1, 45],
            },
            "RELEND": {
                "dimensions": ["numpoint"],
                "name": "RELEND",
                "ncattrs": {
                    "long_name": "release "
                    "end "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELKINDZ": {
                "dimensions": ["numpoint"],
                "name": "RELKINDZ",
                "ncattrs": {"long_name": "release " "kind"},
                "shape": [1],
            },
            "RELLAT1": {
                "dimensions": ["numpoint"],
                "name": "RELLAT1",
                "ncattrs": {
                    "long_name": "release " "latitude " "lower " "left " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLAT2": {
                "dimensions": ["numpoint"],
                "name": "RELLAT2",
                "ncattrs": {
                    "long_name": "release " "latitude " "upper " "right " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLNG1": {
                "dimensions": ["numpoint"],
                "name": "RELLNG1",
                "ncattrs": {
                    "long_name": "release " "longitude " "lower " "left " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELLNG2": {
                "dimensions": ["numpoint"],
                "name": "RELLNG2",
                "ncattrs": {
                    "long_name": "release " "longitude " "upper " "right " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELPART": {
                "dimensions": ["numpoint"],
                "name": "RELPART",
                "ncattrs": {"long_name": "number " "of " "release " "particles"},
                "shape": [1],
            },
            "RELSTART": {
                "dimensions": ["numpoint"],
                "name": "RELSTART",
                "ncattrs": {
                    "long_name": "release "
                    "start "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELXMASS": {
                "dimensions": ["numspec", "numpoint"],
                "name": "RELXMASS",
                "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                "shape": [1, 1],
            },
            "RELZZ1": {
                "dimensions": ["numpoint"],
                "name": "RELZZ1",
                "ncattrs": {
                    "long_name": "release " "height " "bottom",
                    "units": "meters",
                },
                "shape": [1],
            },
            "RELZZ2": {
                "dimensions": ["numpoint"],
                "name": "RELZZ2",
                "ncattrs": {"long_name": "release " "height " "top", "units": "meters"},
                "shape": [1],
            },
            "WD_spec001": {
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "name": "WD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "dquer": 0.6,
                    "henry": 0.0,
                    "long_name": "Cs-137_wet_deposition",
                    "units": "1e-12 kg " "m-2",
                    "weta": 7e-05,
                    "wetb": 0.8,
                },
                "shape": [1, 1, 11, 30, 40],
            },
            "fptot": {
                "dimensions": ["noutrel", "rlat", "rlon"],
                "name": "fptot",
                "ncattrs": {
                    "coordinates": "lon lat",
                    "long_name": "total_footprint",
                    "sampling_height": "undefined",
                    "units": "ng kg-1",
                },
                "shape": [1, 30, 40],
            },
            "level": {
                "dimensions": ["level"],
                "name": "level",
                "ncattrs": {
                    "axis": "Z",
                    "description": "grid " "cell top",
                    "long_name": "height " "above " "ground",
                    "positive": "up",
                    "standard_name": "height",
                    "units": "meters",
                },
                "shape": [3],
            },
            "rlat": {
                "dimensions": ["rlat"],
                "name": "rlat",
                "ncattrs": {
                    "axis": "Y",
                    "description": "grid cell " "centers",
                    "long_name": "latitude in " "rotated " "pole grid",
                    "standard_name": "grid_latitude",
                    "units": "degrees",
                },
                "shape": [30],
            },
            "rlon": {
                "dimensions": ["rlon"],
                "name": "rlon",
                "ncattrs": {
                    "axis": "X",
                    "description": "grid cell " "centers",
                    "long_name": "longitude " "in rotated " "pole grid",
                    "standard_name": "grid_longitude",
                    "units": "degrees",
                },
                "shape": [40],
            },
            "rotated_pole": {
                "dimensions": {},
                "name": "rotated_pole",
                "ncattrs": {
                    "grid_mapping_name": "rotated_latitude_longitude",
                    "grid_north_pole_latitude": 43.0,
                    "grid_north_pole_longitude": -170.0,
                },
                "shape": {},
            },
            "spec001": {
                "dimensions": ["nageclass", "noutrel", "time", "level", "rlat", "rlon"],
                "name": "spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "decay": 7.3265155e-10,
                    "long_name": "Cs-137",
                    "ohreact": -9.9e-09,
                    "spec_ass": -9,
                    "units": "ng kg-1",
                    "vsetaver": -0.0003866022,
                    "weightmolar": -9.99,
                },
                "shape": [1, 1, 11, 3, 30, 40],
            },
            "time": {
                "dimensions": ["time"],
                "name": "time",
                "ncattrs": {
                    "calendar": "proleptic_gregorian",
                    "units": "seconds since " "2019-09-30 " "12:00",
                },
                "shape": [11],
            },
        },
    },
    "rotated_pole": True,
    "time_stats": {
        "max": 0.15455759,
        "mean": 0.0004015538,
        "mean_nz": 0.0012772315,
        "median": 0.0,
        "median_nz": 0.00020140434,
    },
    "type": "Field",
    "var_setups": [
        {
            "combine_species": True,
            "deposition_type": "dry",
            "domain": "auto",
            "ens_member_id": None,
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "infile": "data/cosmo-1_2019052800.nc",
            "integrate": True,
            "lang": "de",
            "level": None,
            "nageclass": [0],
            "noutrel": [0],
            "numpoint": [0],
            "outfile": "plot.png",
            "plot_type": "auto",
            "simulation_type": "deterministic",
            "species_id": [1],
            "time": [10],
            "variable": "deposition",
        },
        {
            "combine_species": True,
            "deposition_type": "wet",
            "domain": "auto",
            "ens_member_id": None,
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "infile": "data/cosmo-1_2019052800.nc",
            "integrate": True,
            "lang": "de",
            "level": None,
            "nageclass": [0],
            "noutrel": [0],
            "numpoint": [0],
            "outfile": "plot.png",
            "plot_type": "auto",
            "simulation_type": "deterministic",
            "species_id": [1],
            "time": [10],
            "variable": "deposition",
        },
    ],
}

plot_summary = {
    "ax_map": {"type": "MapAxesRotatedPole"},
    "boxes": {
        "method:Plot.fill_box_bottom": {
            "dx_unit": 0.00790513833992095,
            "dy_unit": 0.33646003493715526,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "small", "va": "top"},
                    "loc": {
                        "dx": -0.7,
                        "dx_unit": 0.00790513833992095,
                        "dy": 0.5,
                        "dy_unit": 0.33646003493715526,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.003952569169960475,
                        "x0": 0.009486166007905139,
                        "y": 0.7644779755439912,
                        "y0": 0.5962479580754136,
                    },
                    "replace_edge_spaces": False,
                    "s": "FLEXPART "
                    "basierend auf "
                    "COSMO-1, "
                    "2019-09-30 "
                    "12:00 UTC",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "small", "va": "top"},
                    "loc": {
                        "dx": 0.7,
                        "dx_unit": 0.00790513833992095,
                        "dy": 0.5,
                        "dy_unit": 0.33646003493715526,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.9960474308300395,
                        "x0": 0.9905138339920949,
                        "y": 0.7644779755439912,
                        "y0": 0.5962479580754136,
                    },
                    "replace_edge_spaces": False,
                    "s": "©MeteoSchweiz",
                    "type": "TextBoxElement_Text",
                },
            ],
            "lw_frame": None,
            "name": "bottom",
            "rect": [0.05, 0.026966060764252245, 0.980375, 0.023033939235747758],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_bottom": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.01869547167213426,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": -1.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.9588699623213046,
                        "y0": 0.9775654339934389,
                    },
                    "replace_edge_spaces": False,
                    "s": "Freisetzung",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.0504777735147625,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschexponent:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 4.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.09721645269509815,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschkoeff.:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 6.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.1439551318754338,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Sediment.-Geschw.:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 9.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.19069381105576944,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Deposit.-Geschw.:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 11.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.23743249023610508,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Halbwertszeit:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 14.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.28417116941644077,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Substanz:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.37764852777711205,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Totale " "Masse:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 21.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.4243872069574477,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Rate:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 24.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.4711258861377834,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ende:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 26.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.517864565318119,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Start:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.6113419236787903,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": 'H$\\mathrm{\\"o}$he:',
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 34.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.658080602859126,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": 'L$\\mathrm{\\"a}$nge:',
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 36.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.7048192820394616,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Breite:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 39.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.7515579612197972,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort:",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.0504777735147625,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 4.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.09721645269509815,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 6.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.1439551318754338,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 9.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.19069381105576944,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 11.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.23743249023610508,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "30",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 14.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.28417116941644077,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.37764852777711205,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "1e+09",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 21.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.4243872069574477,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "34722",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 24.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.4711258861377834,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-09-30 " "20:00 UTC",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 26.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.517864565318119,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-09-30 " "12:00 UTC",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.6113419236787903,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "100",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 34.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.658080602859126,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "7$^\\circ$$\\,$0'$\\,$O " "(7.0000$^\\circ$$\\,$O)",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 36.5,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.7048192820394616,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": "47$^\\circ$$\\,$0'$\\,$N " "(47.0000$^\\circ$$\\,$N)",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 39.0,
                        "dy_unit": 0.01869547167213426,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.7515579612197972,
                        "y0": 0.022434566006561112,
                    },
                    "replace_edge_spaces": False,
                    "s": 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElement_Text",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/bottom",
            "rect": [0.8366250000000001, 0.05, 0.19375, 0.41453888598870897],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_top": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.022945348513305826,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 1.0068836045539917,
                        "y0": 0.972465581784033,
                    },
                    "replace_edge_spaces": False,
                    "s": "Deposition " "(Bq h m-2)",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 7.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.1996245320657607,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-09 $\\tt " "-$ 1E-08",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 10.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.26846057760567815,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-08 $\\tt " "-$ 1E-07",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 13.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.3372966231455956,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-07 $\\tt " "-$ 1E-06",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 16.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.4061326686855131,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-06 $\\tt " "-$ 1E-05",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.4749687142254306,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-05 $\\tt " "-$ 1E-04",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 22.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.5438047597653481,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-04 $\\tt " "-$ 0.001",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 25.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.6126408053052655,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "0.001 $\\tt " "-$ 0.01 ",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 28.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.6814768508451831,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": " 0.01 $\\tt " "-$ 0.1  ",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.7503128963851006,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "      $\\tt " "\\geq$ 0.1  ",
                    "type": "TextBoxElement_Text",
                },
                {
                    "ec": "black",
                    "fc": [0.8784313725490196, 0.7686274509803922, 0.6745098039215687],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 7.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.19044639266043836,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.8666666666666667, 0.4980392156862745, 0.8431372549019608],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 10.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.2592824382003558,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.38823529411764707, 0.0, 1.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 13.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.3281184837402733,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.39215686274509803, 0.6, 0.7803921568627451],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 16.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.3969545292801908,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [
                        0.13333333333333333,
                        0.5450980392156862,
                        0.13333333333333333,
                    ],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.46579057482010827,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.36470588235294116, 1.0, 0.00784313725490196],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 22.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.5346266203600258,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7803921568627451, 1.0, 0.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 25.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.6034626658999432,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [1.0, 0.9372549019607843, 0.2235294117647059],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 28.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.6722987114398608,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7843137254901961, 0.7843137254901961, 0.7843137254901961],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.1,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.7411347569797783,
                        "y0": 0.02753441821596699,
                    },
                    "type": "TextBoxElement_ColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "kwargs": {
                        "markeredgecolor": "red",
                        "markeredgewidth": 1.5,
                        "markerfacecolor": "white",
                        "markersize": 7.5,
                    },
                    "loc": {
                        "dx": -8.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.95,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.17999999999999988,
                        "x0": 0.5,
                        "y": 0.04933249930360752,
                        "y0": 0.02753441821596699,
                    },
                    "m": "^",
                    "type": "TextBoxElement_Marker",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.25,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.03327075534429345,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "Abgabeort",
                    "type": "TextBoxElement_Text",
                },
                {
                    "kwargs": {
                        "color": "black",
                        "markeredgewidth": 1.5,
                        "markersize": 10,
                    },
                    "loc": {
                        "dx": -8.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 3.95,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.17999999999999988,
                        "x0": 0.5,
                        "y": 0.118168544843525,
                        "y0": 0.02753441821596699,
                    },
                    "m": "+",
                    "type": "TextBoxElement_Marker",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 3.25,
                        "dy_unit": 0.022945348513305826,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.10210680088421092,
                        "y0": 0.02753441821596699,
                    },
                    "replace_edge_spaces": False,
                    "s": "Max.: 0.155",
                    "type": "TextBoxElement_Text",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/top",
            "rect": [
                0.8366250000000001,
                0.480038885988709,
                0.19375,
                0.3377590885362164,
            ],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_left": {
            "dx_unit": 0.01,
            "dy_unit": 0.10093801048114658,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.10093801048114658,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.012,
                        "x0": 0.012,
                        "y": 0.8788743874226241,
                        "y0": 0.8788743874226241,
                    },
                    "replace_edge_spaces": False,
                    "s": "Totale " "Bodendeposition",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.10093801048114658,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.012,
                        "x0": 0.012,
                        "y": 0.12112561257737589,
                        "y0": 0.12112561257737589,
                    },
                    "replace_edge_spaces": False,
                    "s": "Akkumuliert "
                    '$\\mathrm{\\"u}$ber '
                    "33$\\,$h "
                    "(seit "
                    "+00:00$\\,$h)",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.10093801048114658,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.988,
                        "x0": 0.988,
                        "y": 0.8788743874226241,
                        "y0": 0.8788743874226241,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-10-01 " "21:00 UTC " "(+33:00$\\,$h)",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.10093801048114658,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.988,
                        "x0": 0.988,
                        "y": 0.12112561257737589,
                        "y0": 0.12112561257737589,
                    },
                    "replace_edge_spaces": False,
                    "s": "33:00$\\,$h " "seit " "Freisetzungsbeginn",
                    "type": "TextBoxElement_Text",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/left",
            "rect": [0.05, 0.8332979745249253, 0.775, 0.07677979745249253],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_right": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.10093801048114658,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.0,
                        "dy_unit": 0.10093801048114658,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.8788743874226241,
                        "y0": 0.8788743874226241,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137",
                    "type": "TextBoxElement_Text",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.0,
                        "dy_unit": 0.10093801048114658,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.12112561257737589,
                        "y0": 0.12112561257737589,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort: " 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElement_Text",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/right",
            "rect": [
                0.8366250000000001,
                0.8332979745249253,
                0.19375,
                0.07677979745249253,
            ],
            "type": "TextBoxAxes",
        },
    },
    "draw_colors": True,
    "draw_contours": False,
    "field": {
        "fld": {
            "dtype": "float32",
            "n_nan": 0,
            "n_zero": 545,
            "nanmax": 0.15455633,
            "nanmax_nonzero": 0.15455633,
            "nanmean": 0.0008733995,
            "nanmean_nonzero": 0.0016001214,
            "nanmedian": 1.5417452e-05,
            "nanmedian_nonzero": 0.0003491032,
            "nanmin": 0.0,
            "nanmin_nonzero": 4.145933e-09,
            "shape": [30, 40],
        },
        "lat": {"dtype": "float32", "max": 2.9499998, "min": -1.4000003, "shape": [30]},
        "lon": {"dtype": "float32", "max": 4.0499997, "min": -1.7999997, "shape": [40]},
        "nc_meta_data": {
            "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
            "dimensions": {
                "level": {"name": "level", "size": 3},
                "nageclass": {"name": "nageclass", "size": 1},
                "nchar": {"name": "nchar", "size": 45},
                "noutrel": {"name": "noutrel", "size": 1},
                "numpoint": {"name": "numpoint", "size": 1},
                "numspec": {"name": "numspec", "size": 1},
                "rlat": {"name": "rlat", "size": 30},
                "rlon": {"name": "rlon", "size": 40},
                "time": {"name": "time", "size": 11},
            },
            "ncattrs": {"dxout": 0.01, "dyout": 0.01},
            "variables": {
                "DD_spec001": {
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "name": "DD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "density": 2500.0,
                        "dquer": 0.6,
                        "dryvel": 0.0015,
                        "dsigma": 0.3,
                        "f0": 0.0,
                        "henry": 0.0,
                        "long_name": "Cs-137_dry_deposition",
                        "reldiff": -9.9,
                        "units": "1e-12 " "kg " "m-2",
                    },
                    "shape": [1, 1, 11, 30, 40],
                },
                "LAGE": {
                    "dimensions": ["nageclass"],
                    "name": "LAGE",
                    "ncattrs": {"long_name": "age " "class", "units": "seconds"},
                    "shape": [1],
                },
                "RELCOM": {
                    "dimensions": ["numpoint", "nchar"],
                    "name": "RELCOM",
                    "ncattrs": {"long_name": "release " "point " "name"},
                    "shape": [1, 45],
                },
                "RELEND": {
                    "dimensions": ["numpoint"],
                    "name": "RELEND",
                    "ncattrs": {
                        "long_name": "release "
                        "end "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELKINDZ": {
                    "dimensions": ["numpoint"],
                    "name": "RELKINDZ",
                    "ncattrs": {"long_name": "release " "kind"},
                    "shape": [1],
                },
                "RELLAT1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT1",
                    "ncattrs": {
                        "long_name": "release " "latitude " "lower " "left " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLAT2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT2",
                    "ncattrs": {
                        "long_name": "release " "latitude " "upper " "right " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLNG1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG1",
                    "ncattrs": {
                        "long_name": "release " "longitude " "lower " "left " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELLNG2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG2",
                    "ncattrs": {
                        "long_name": "release " "longitude " "upper " "right " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELPART": {
                    "dimensions": ["numpoint"],
                    "name": "RELPART",
                    "ncattrs": {"long_name": "number " "of " "release " "particles"},
                    "shape": [1],
                },
                "RELSTART": {
                    "dimensions": ["numpoint"],
                    "name": "RELSTART",
                    "ncattrs": {
                        "long_name": "release "
                        "start "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELXMASS": {
                    "dimensions": ["numspec", "numpoint"],
                    "name": "RELXMASS",
                    "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                    "shape": [1, 1],
                },
                "RELZZ1": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ1",
                    "ncattrs": {
                        "long_name": "release " "height " "bottom",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "RELZZ2": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ2",
                    "ncattrs": {
                        "long_name": "release " "height " "top",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "WD_spec001": {
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "name": "WD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "dquer": 0.6,
                        "henry": 0.0,
                        "long_name": "Cs-137_wet_deposition",
                        "units": "1e-12 " "kg " "m-2",
                        "weta": 7e-05,
                        "wetb": 0.8,
                    },
                    "shape": [1, 1, 11, 30, 40],
                },
                "fptot": {
                    "dimensions": ["noutrel", "rlat", "rlon"],
                    "name": "fptot",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "long_name": "total_footprint",
                        "sampling_height": "undefined",
                        "units": "ng " "kg-1",
                    },
                    "shape": [1, 30, 40],
                },
                "level": {
                    "dimensions": ["level"],
                    "name": "level",
                    "ncattrs": {
                        "axis": "Z",
                        "description": "grid " "cell " "top",
                        "long_name": "height " "above " "ground",
                        "positive": "up",
                        "standard_name": "height",
                        "units": "meters",
                    },
                    "shape": [3],
                },
                "rlat": {
                    "dimensions": ["rlat"],
                    "name": "rlat",
                    "ncattrs": {
                        "axis": "Y",
                        "description": "grid " "cell " "centers",
                        "long_name": "latitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_latitude",
                        "units": "degrees",
                    },
                    "shape": [30],
                },
                "rlon": {
                    "dimensions": ["rlon"],
                    "name": "rlon",
                    "ncattrs": {
                        "axis": "X",
                        "description": "grid " "cell " "centers",
                        "long_name": "longitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_longitude",
                        "units": "degrees",
                    },
                    "shape": [40],
                },
                "rotated_pole": {
                    "dimensions": {},
                    "name": "rotated_pole",
                    "ncattrs": {
                        "grid_mapping_name": "rotated_latitude_longitude",
                        "grid_north_pole_latitude": 43.0,
                        "grid_north_pole_longitude": -170.0,
                    },
                    "shape": {},
                },
                "spec001": {
                    "dimensions": [
                        "nageclass",
                        "noutrel",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "name": "spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "decay": 7.3265155e-10,
                        "long_name": "Cs-137",
                        "ohreact": -9.9e-09,
                        "spec_ass": -9,
                        "units": "ng " "kg-1",
                        "vsetaver": -0.0003866022,
                        "weightmolar": -9.99,
                    },
                    "shape": [1, 1, 11, 3, 30, 40],
                },
                "time": {
                    "dimensions": ["time"],
                    "name": "time",
                    "ncattrs": {
                        "calendar": "proleptic_gregorian",
                        "units": "seconds " "since " "2019-09-30 " "12:00",
                    },
                    "shape": [11],
                },
            },
        },
        "rotated_pole": True,
        "time_stats": {
            "max": 0.15455759,
            "mean": 0.0004015538,
            "mean_nz": 0.0012772315,
            "median": 0.0,
            "median_nz": 0.00020140434,
        },
        "type": "Field",
        "var_setups": [
            {
                "combine_species": True,
                "deposition_type": "dry",
                "domain": "auto",
                "ens_member_id": None,
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "infile": "data/cosmo-1_2019052800.nc",
                "integrate": True,
                "lang": "de",
                "level": None,
                "nageclass": [0],
                "noutrel": [0],
                "numpoint": [0],
                "outfile": "plot.png",
                "plot_type": "auto",
                "simulation_type": "deterministic",
                "species_id": [1],
                "time": [10],
                "variable": "deposition",
            },
            {
                "combine_species": True,
                "deposition_type": "wet",
                "domain": "auto",
                "ens_member_id": None,
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "infile": "data/cosmo-1_2019052800.nc",
                "integrate": True,
                "lang": "de",
                "level": None,
                "nageclass": [0],
                "noutrel": [0],
                "numpoint": [0],
                "outfile": "plot.png",
                "plot_type": "auto",
                "simulation_type": "deterministic",
                "species_id": [1],
                "time": [10],
                "variable": "deposition",
            },
        ],
    },
    "fig": {
        "axes": [
            {
                "bbox": {
                    "bounds": (
                        60.0,
                        45.00000000000005,
                        930.0000000000001,
                        691.0181770724328,
                    ),
                    "type": "TransformedBbox",
                },
                "type": "GeoAxesSubplot",
            },
            {
                "bbox": {
                    "bounds": (
                        60.0,
                        749.9681770724327,
                        930.0000000000001,
                        69.1018177072433,
                    ),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 749.9681770724327, 232.5, 69.1018177072433),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 432.03499738983805, 232.5, 303.9831796825947),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 45.0, 232.5, 373.08499738983807),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (60.0, 24.26945468782702, 1176.45, 20.73054531217298),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
        ],
        "bbox": {"bounds": (0.0, 0.0, 1200.0, 900.0), "type": "TransformedBbox"},
        "type": "Figure",
    },
    "map_conf": {
        "geo_res": "10m",
        "geo_res_cities": "50m",
        "geo_res_rivers": "50m",
        "lang": "de",
        "lw_frame": 1.0,
        "min_city_pop": 300000,
        "ref_dist_conf": {
            "dist": 100,
            "pos": "bl",
            "type": "RefDistIndConf",
            "unit": "km",
        },
        "ref_dist_on": True,
        "rel_offset": [0.0, 0.0],
        "type": "MapAxesConf_Cosmo1",
        "zoom_fact": 1.02,
    },
    "mark_release_site": True,
    "type": "Plot",
}
