# -*- coding: utf-8 -*-
# flake8: noqa
"""
Test reference for pytest test.

tests/slow/pyflexplot/test_plots/shared.py
    ::Test_IntegratedConcentration
    ::test

Created by temporarily changing the parent class of
``Test_IntegratedConcentration``
from ``_TestBase`` to ``_TestCreateReference`` and running pytest.
"""

field_summary = {
    "type": "Field",
    "rotated_pole": True,
    "var_setups": [
        {
            "infile": "flexpart_cosmo-1_2019093012.nc",
            "outfile": "plot.png",
            "input_variable": "concentration",
            "plot_variable": "auto",
            "ens_variable": "none",
            "plot_type": "auto",
            "deposition_type": "none",
            "integrate": True,
            "combine_species": False,
            "ens_member_id": None,
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "ens_param_time_win": None,
            "lang": "en",
            "domain": "ch",
            "nageclass": [0],
            "noutrel": [0],
            "numpoint": [0],
            "species_id": [1],
            "time": [10],
            "level": [0],
        }
    ],
    "time_stats": {
        "mean": 5.7065587e-05,
        "median": 0.0,
        "mean_nz": 0.00016808025,
        "median_nz": 2.5472184e-05,
        "max": 0.038744926,
    },
    "nc_meta_data": {
        "ncattrs": {"dxout": 0.01, "dyout": 0.01},
        "dimensions": {
            "time": {"name": "time", "size": 12},
            "rlon": {"name": "rlon", "size": 40},
            "rlat": {"name": "rlat", "size": 30},
            "level": {"name": "level", "size": 3},
            "numspec": {"name": "numspec", "size": 1},
            "numpoint": {"name": "numpoint", "size": 1},
            "noutrel": {"name": "noutrel", "size": 1},
            "nageclass": {"name": "nageclass", "size": 1},
            "nchar": {"name": "nchar", "size": 45},
        },
        "variables": {
            "time": {
                "name": "time",
                "dimensions": ["time"],
                "shape": [12],
                "ncattrs": {
                    "units": "seconds since 2019-09-30 12:00",
                    "calendar": "proleptic_gregorian",
                },
            },
            "rlon": {
                "name": "rlon",
                "dimensions": ["rlon"],
                "shape": [40],
                "ncattrs": {
                    "long_name": "longitude in rotated pole grid",
                    "units": "degrees",
                    "standard_name": "grid_longitude",
                    "axis": "X",
                    "description": "grid cell centers",
                },
            },
            "rlat": {
                "name": "rlat",
                "dimensions": ["rlat"],
                "shape": [30],
                "ncattrs": {
                    "long_name": "latitude in rotated pole grid",
                    "units": "degrees",
                    "standard_name": "grid_latitude",
                    "axis": "Y",
                    "description": "grid cell centers",
                },
            },
            "level": {
                "name": "level",
                "dimensions": ["level"],
                "shape": [3],
                "ncattrs": {
                    "axis": "Z",
                    "units": "meters",
                    "positive": "up",
                    "standard_name": "height",
                    "long_name": "height above ground",
                    "description": "grid cell top",
                },
            },
            "rotated_pole": {
                "name": "rotated_pole",
                "dimensions": {},
                "shape": {},
                "ncattrs": {
                    "grid_mapping_name": "rotated_latitude_longitude",
                    "grid_north_pole_latitude": 43.0,
                    "grid_north_pole_longitude": -170.0,
                },
            },
            "RELCOM": {
                "name": "RELCOM",
                "dimensions": ["numpoint", "nchar"],
                "shape": [1, 45],
                "ncattrs": {"long_name": "release point name"},
            },
            "RELLNG1": {
                "name": "RELLNG1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_east",
                    "long_name": "release longitude lower left corner",
                },
            },
            "RELLNG2": {
                "name": "RELLNG2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_east",
                    "long_name": "release longitude upper right corner",
                },
            },
            "RELLAT1": {
                "name": "RELLAT1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_north",
                    "long_name": "release latitude lower left corner",
                },
            },
            "RELLAT2": {
                "name": "RELLAT2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_north",
                    "long_name": "release latitude upper right corner",
                },
            },
            "RELZZ1": {
                "name": "RELZZ1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"units": "meters", "long_name": "release height bottom"},
            },
            "RELZZ2": {
                "name": "RELZZ2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"units": "meters", "long_name": "release height top"},
            },
            "RELKINDZ": {
                "name": "RELKINDZ",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"long_name": "release kind"},
            },
            "RELSTART": {
                "name": "RELSTART",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "seconds",
                    "long_name": "release start relative to simulation start",
                },
            },
            "RELEND": {
                "name": "RELEND",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "seconds",
                    "long_name": "release end relative to simulation start",
                },
            },
            "RELPART": {
                "name": "RELPART",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"long_name": "number of release particles"},
            },
            "RELXMASS": {
                "name": "RELXMASS",
                "dimensions": ["numspec", "numpoint"],
                "shape": [1, 1],
                "ncattrs": {"long_name": "total release particle mass"},
            },
            "LAGE": {
                "name": "LAGE",
                "dimensions": ["nageclass"],
                "shape": [1],
                "ncattrs": {"units": "seconds", "long_name": "age class"},
            },
            "spec001": {
                "name": "spec001",
                "dimensions": ["nageclass", "noutrel", "time", "level", "rlat", "rlon"],
                "shape": [1, 1, 11, 3, 30, 40],
                "ncattrs": {
                    "units": "ng kg-1",
                    "long_name": "Cs-137",
                    "coordinates": "lon lat",
                    "decay": 7.3265155e-10,
                    "weightmolar": -9.99,
                    "ohreact": -9.9e-09,
                    "vsetaver": -0.0003866022,
                    "spec_ass": -9,
                },
            },
            "WD_spec001": {
                "name": "WD_spec001",
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 40],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "Cs-137_wet_deposition",
                    "coordinates": "lon lat",
                    "weta": 7e-05,
                    "wetb": 0.8,
                    "dquer": 0.6,
                    "henry": 0.0,
                },
            },
            "DD_spec001": {
                "name": "DD_spec001",
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 40],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "Cs-137_dry_deposition",
                    "coordinates": "lon lat",
                    "dryvel": 0.0015,
                    "reldiff": -9.9,
                    "henry": 0.0,
                    "f0": 0.0,
                    "dquer": 0.6,
                    "density": 2500.0,
                    "dsigma": 0.3,
                },
            },
            "fptot": {
                "name": "fptot",
                "dimensions": ["noutrel", "rlat", "rlon"],
                "shape": [1, 30, 40],
                "ncattrs": {
                    "coordinates": "lon lat",
                    "units": "ng kg-1",
                    "long_name": "total_footprint",
                    "sampling_height": "undefined",
                },
            },
        },
        "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
    },
    "fld": {
        "dtype": "float32",
        "shape": [30, 40],
        "nanmin": 0.0,
        "nanmean": 9.7421966e-05,
        "nanmedian": 6.8192676e-06,
        "nanmax": 0.038744926,
        "nanmin_nonzero": 5.969089e-10,
        "nanmean_nonzero": 0.00016724801,
        "nanmedian_nonzero": 3.904104e-05,
        "nanmax_nonzero": 0.038744926,
        "n_nan": 0,
        "n_zero": 501,
    },
    "lat": {"dtype": "float32", "shape": [30], "min": -1.4000003, "max": 2.9499998},
    "lon": {"dtype": "float32", "shape": [40], "min": -1.7999997, "max": 4.0499997},
}

plot_summary = {
    "type": "BoxedPlot",
    "ax_map": {
        "type": "MapAxesRotatedPole",
        "fig": {
            "type": "Figure",
            "axes": {"type": "bbox"},
            "bbox": {"type": "TransformedBbox", "bounds": [0.0, 0.0, 1250.0, 800.0]},
        },
        "rect": [0.0, 0.05, 0.7872, 0.85],
        "lat": [
            -1.4000003,
            -1.2500002,
            -1.1000004,
            -0.9500003,
            -0.8000002,
            -0.65000033,
            -0.50000024,
            -0.35000038,
            -0.20000029,
            -0.05000019,
            0.099999905,
            0.24999952,
            0.39999962,
            0.5499997,
            0.6999998,
            0.8499999,
            0.9999995,
            1.1499996,
            1.2999997,
            1.4499998,
            1.5999994,
            1.7499995,
            1.8999996,
            2.0499997,
            2.1999998,
            2.3499994,
            2.4999995,
            2.6499996,
            2.7999997,
            2.9499998,
        ],
        "lon": [
            -1.7999997,
            -1.6500001,
            -1.5,
            -1.3499999,
            -1.1999998,
            -1.0500002,
            -0.9000001,
            -0.75,
            -0.5999999,
            -0.4499998,
            -0.3000002,
            -0.1500001,
            0.0,
            0.1500001,
            0.3000002,
            0.4499998,
            0.5999999,
            0.75,
            0.9000001,
            1.0500002,
            1.2000003,
            1.3499999,
            1.4999995,
            1.6500001,
            1.7999997,
            1.9500003,
            2.1,
            2.2499995,
            2.4,
            2.5499997,
            2.7000003,
            2.85,
            2.9999995,
            3.15,
            3.2999997,
            3.4500003,
            3.6,
            3.7499995,
            3.9,
            4.0499997,
        ],
        "conf": {
            "type": "MapAxesConf",
            "geo_res": "10m",
            "geo_res_cities": "10m",
            "geo_res_rivers": "10m",
            "lang": "en",
            "lllat": None,
            "lllon": None,
            "lw_frame": 1.0,
            "min_city_pop": 0,
            "urlat": None,
            "urlon": None,
            "ref_dist_conf": {
                "type": "RefDistIndConf",
                "dist": 25,
                "font_size": 11.0,
                "pos": "bl",
                "unit": "km",
            },
            "ref_dist_on": True,
            "rel_offset": [-0.02, 0.045],
            "zoom_fact": 3.6,
        },
    },
    "boxes": {
        "top": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.0, 0.92, 0.7872, 0.08],
            "name": "top",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.009527439024390244,
            "dy_unit": 0.11250000000000004,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.009527439024390244,
                        "y0": 0.8875,
                        "x": 0.009527439024390244,
                        "y": 0.8875,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Integrated activity concentration of Cs-137",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 14.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.009527439024390244,
                        "y0": 0.11250000000000004,
                        "x": 0.009527439024390244,
                        "y": 0.11250000000000004,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": "Summed over 30:00$\\,$h since +0:00$\\,$h",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.9904725609756098,
                        "y0": 0.8875,
                        "x": 0.9904725609756098,
                        "y": 0.8875,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "2019-10-01 18:00 UTC (+30:00$\\,$h)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.9904725609756098,
                        "y0": 0.11250000000000004,
                        "x": 0.9904725609756098,
                        "y": 0.11250000000000004,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": '30:00$\\,$h since release start at G$\\mathrm{\\"o}$sgen',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "right",
                        "va": "baseline",
                    },
                },
            ],
        },
        "right_top": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.8, 0.85, 0.2, 0.15],
            "name": "right_top",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.059999999999999984,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.059999999999999984,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.5,
                        "y0": 0.9400000000000001,
                        "x": 0.5,
                        "y": 0.9400000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Data",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "center",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.059999999999999984,
                        "dx": 0.0,
                        "dy": -4.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9400000000000001,
                        "x": 0.037500000000000006,
                        "y": 0.7000000000000002,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Input variable:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.059999999999999984,
                        "dx": 0.0,
                        "dy": -6.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9400000000000001,
                        "x": 0.037500000000000006,
                        "y": 0.5500000000000002,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Level:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.059999999999999984,
                        "dx": 0.0,
                        "dy": -4.0,
                        "x0": 0.9625,
                        "y0": 0.9400000000000001,
                        "x": 0.9625,
                        "y": 0.7000000000000002,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "Activity concentration",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.059999999999999984,
                        "dx": 0.0,
                        "dy": -6.5,
                        "x0": 0.9625,
                        "y0": 0.9400000000000001,
                        "x": 0.9625,
                        "y": 0.5500000000000002,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "0$-$500 m AGL",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
            ],
        },
        "right_middle": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.8, 0.49, 0.2, 0.33999999999999997],
            "name": "right_middle",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.02647058823529411,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.5,
                        "y": 0.9735294117647059,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Int. concentr. (Bq h m$^{-3}$)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "center",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -5.0,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.8411764705882353,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "      $\\tt \\geq$ 0.01 ",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -7.5,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.775,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "0.001 $\\tt -$ 0.01 ",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -10.0,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.7088235294117647,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-04 $\\tt -$ 0.001",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -12.5,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.6426470588235295,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-05 $\\tt -$ 1E-04",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -15.0,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.5764705882352943,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-06 $\\tt -$ 1E-05",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -17.5,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.510294117647059,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-07 $\\tt -$ 1E-06",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -20.0,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.4441176470588236,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-08 $\\tt -$ 1E-07",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -22.5,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.37794117647058834,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-09 $\\tt -$ 1E-08",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -6.6,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.7988235294117647,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "lightgray",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -9.1,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.7326470588235294,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "yellow",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -11.6,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.6664705882352941,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "greenyellow",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -14.1,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.6002941176470589,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "yellowgreen",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -16.6,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.5341176470588236,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "cornflowerblue",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -19.1,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.4679411764705883,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "rebeccapurple",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -21.6,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.401764705882353,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "violet",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -10,
                        "dy": -24.1,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.12499999999999994,
                        "y": 0.33558823529411774,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "bisque",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementMarker",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -8.0,
                        "dy": -26.55,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.19999999999999996,
                        "y": 0.2707352941176472,
                        "va": "top",
                        "ha": "center",
                    },
                    "m": "^",
                    "kwargs": {
                        "markeredgecolor": "red",
                        "markerfacecolor": "white",
                        "markersize": 7.5,
                        "markeredgewidth": 1.5,
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -25.85,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.2892647058823531,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Release site",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementMarker",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -8.0,
                        "dy": -29.05,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.19999999999999996,
                        "y": 0.2045588235294119,
                        "va": "top",
                        "ha": "center",
                    },
                    "m": "+",
                    "kwargs": {
                        "color": "black",
                        "markersize": 10,
                        "markeredgewidth": 1.5,
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.02647058823529411,
                        "dx": -3,
                        "dy": -28.35,
                        "x0": 0.5,
                        "y0": 0.9735294117647059,
                        "x": 0.38749999999999996,
                        "y": 0.2230882352941178,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Max.: 0.0387",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "va": "top",
                    },
                },
            ],
        },
        "right_bottom": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.8, 0.05, 0.2, 0.42],
            "name": "right_bottom",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.021428571428571425,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.5,
                        "y0": 0.9785714285714285,
                        "x": 0.5,
                        "y": 0.9785714285714285,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Release",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "center",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -4.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.8928571428571428,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Site:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -6.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.8392857142857143,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Latitude:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -9.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.7857142857142857,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Longitude:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -11.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.7321428571428572,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Height:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -16.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.625,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Start:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -19.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.5714285714285714,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "End:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -21.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.5178571428571429,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Rate:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -24.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.4642857142857143,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Total mass:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -29.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.3571428571428572,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Substance:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -31.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.3035714285714286,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Half-life:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -34.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.2500000000000001,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Deposit. vel.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -36.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.1964285714285715,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Sediment. vel.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -39.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.1428571428571429,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Washout coeff.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -41.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9785714285714285,
                        "x": 0.037500000000000006,
                        "y": 0.08928571428571441,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Washout exponent:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -4.0,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.8928571428571428,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": 'G$\\mathrm{\\"o}$sgen',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -6.5,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.8392857142857143,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "47$^\\circ$$\\,$21'$\\,$N (47.3659$^\\circ$$\\,$N)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -9.0,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.7857142857142857,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "7$^\\circ$$\\,$58'$\\,$E (7.9668$^\\circ$$\\,$E)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -11.5,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.7321428571428572,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "100$\\,$m AGL",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -16.5,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.625,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "2019-09-30 12:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -19.0,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.5714285714285714,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "2019-09-30 20:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -21.5,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.5178571428571429,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "34722.2$\\,$Bq s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -24.0,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.4642857142857143,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "1e+09$\\,$Bq",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -29.0,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.3571428571428572,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "Cs-137",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -31.5,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.3035714285714286,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "30.17$\\,$a",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -34.0,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.2500000000000001,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "0.0015$\\,$m s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -36.5,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.1964285714285715,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "0$\\,$m s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -39.0,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.1428571428571429,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "7e-05$\\,$s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.021428571428571425,
                        "dx": 0.0,
                        "dy": -41.5,
                        "x0": 0.9625,
                        "y0": 0.9785714285714285,
                        "x": 0.9625,
                        "y": 0.08928571428571441,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "0.8",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
            ],
        },
        "bottom": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.0, 0.0, 1.0, 0.05],
            "name": "bottom",
            "lw_frame": None,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.0075,
            "dy_unit": 0.17999999999999997,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.0075,
                        "dy_unit": 0.17999999999999997,
                        "dx": -0.7,
                        "dy": 0.5,
                        "x0": 0.0075,
                        "y0": 0.8200000000000001,
                        "x": 0.0022500000000000003,
                        "y": 0.91,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "FLEXPART based on COSMO-1, 2019-09-30 12:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.0075,
                        "dy_unit": 0.17999999999999997,
                        "dx": 0.7,
                        "dy": 0.5,
                        "x0": 0.9925,
                        "y0": 0.8200000000000001,
                        "x": 0.99775,
                        "y": 0.91,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "©MeteoSwiss",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
            ],
        },
    },
    "field": {
        "type": "Field",
        "rotated_pole": True,
        "var_setups": [
            {
                "infile": "flexpart_cosmo-1_2019093012.nc",
                "outfile": "plot.png",
                "input_variable": "concentration",
                "plot_variable": "auto",
                "ens_variable": "none",
                "plot_type": "auto",
                "deposition_type": "none",
                "integrate": True,
                "combine_species": False,
                "ens_member_id": None,
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "ens_param_time_win": None,
                "lang": "en",
                "domain": "ch",
                "nageclass": [0],
                "noutrel": [0],
                "numpoint": [0],
                "species_id": [1],
                "time": [10],
                "level": [0],
            }
        ],
        "time_stats": {
            "mean": 5.7065587e-05,
            "median": 0.0,
            "mean_nz": 0.00016808025,
            "median_nz": 2.5472184e-05,
            "max": 0.038744926,
        },
        "nc_meta_data": {
            "ncattrs": {"dxout": 0.01, "dyout": 0.01},
            "dimensions": {
                "time": {"name": "time", "size": 12},
                "rlon": {"name": "rlon", "size": 40},
                "rlat": {"name": "rlat", "size": 30},
                "level": {"name": "level", "size": 3},
                "numspec": {"name": "numspec", "size": 1},
                "numpoint": {"name": "numpoint", "size": 1},
                "noutrel": {"name": "noutrel", "size": 1},
                "nageclass": {"name": "nageclass", "size": 1},
                "nchar": {"name": "nchar", "size": 45},
            },
            "variables": {
                "time": {
                    "name": "time",
                    "dimensions": ["time"],
                    "shape": [12],
                    "ncattrs": {
                        "units": "seconds since 2019-09-30 12:00",
                        "calendar": "proleptic_gregorian",
                    },
                },
                "rlon": {
                    "name": "rlon",
                    "dimensions": ["rlon"],
                    "shape": [40],
                    "ncattrs": {
                        "long_name": "longitude in rotated pole grid",
                        "units": "degrees",
                        "standard_name": "grid_longitude",
                        "axis": "X",
                        "description": "grid cell centers",
                    },
                },
                "rlat": {
                    "name": "rlat",
                    "dimensions": ["rlat"],
                    "shape": [30],
                    "ncattrs": {
                        "long_name": "latitude in rotated pole grid",
                        "units": "degrees",
                        "standard_name": "grid_latitude",
                        "axis": "Y",
                        "description": "grid cell centers",
                    },
                },
                "level": {
                    "name": "level",
                    "dimensions": ["level"],
                    "shape": [3],
                    "ncattrs": {
                        "axis": "Z",
                        "units": "meters",
                        "positive": "up",
                        "standard_name": "height",
                        "long_name": "height above ground",
                        "description": "grid cell top",
                    },
                },
                "rotated_pole": {
                    "name": "rotated_pole",
                    "dimensions": {},
                    "shape": {},
                    "ncattrs": {
                        "grid_mapping_name": "rotated_latitude_longitude",
                        "grid_north_pole_latitude": 43.0,
                        "grid_north_pole_longitude": -170.0,
                    },
                },
                "RELCOM": {
                    "name": "RELCOM",
                    "dimensions": ["numpoint", "nchar"],
                    "shape": [1, 45],
                    "ncattrs": {"long_name": "release point name"},
                },
                "RELLNG1": {
                    "name": "RELLNG1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_east",
                        "long_name": "release longitude lower left corner",
                    },
                },
                "RELLNG2": {
                    "name": "RELLNG2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_east",
                        "long_name": "release longitude upper right corner",
                    },
                },
                "RELLAT1": {
                    "name": "RELLAT1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_north",
                        "long_name": "release latitude lower left corner",
                    },
                },
                "RELLAT2": {
                    "name": "RELLAT2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_north",
                        "long_name": "release latitude upper right corner",
                    },
                },
                "RELZZ1": {
                    "name": "RELZZ1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "meters",
                        "long_name": "release height bottom",
                    },
                },
                "RELZZ2": {
                    "name": "RELZZ2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"units": "meters", "long_name": "release height top"},
                },
                "RELKINDZ": {
                    "name": "RELKINDZ",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"long_name": "release kind"},
                },
                "RELSTART": {
                    "name": "RELSTART",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "seconds",
                        "long_name": "release start relative to simulation start",
                    },
                },
                "RELEND": {
                    "name": "RELEND",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "seconds",
                        "long_name": "release end relative to simulation start",
                    },
                },
                "RELPART": {
                    "name": "RELPART",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"long_name": "number of release particles"},
                },
                "RELXMASS": {
                    "name": "RELXMASS",
                    "dimensions": ["numspec", "numpoint"],
                    "shape": [1, 1],
                    "ncattrs": {"long_name": "total release particle mass"},
                },
                "LAGE": {
                    "name": "LAGE",
                    "dimensions": ["nageclass"],
                    "shape": [1],
                    "ncattrs": {"units": "seconds", "long_name": "age class"},
                },
                "spec001": {
                    "name": "spec001",
                    "dimensions": [
                        "nageclass",
                        "noutrel",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "shape": [1, 1, 11, 3, 30, 40],
                    "ncattrs": {
                        "units": "ng kg-1",
                        "long_name": "Cs-137",
                        "coordinates": "lon lat",
                        "decay": 7.3265155e-10,
                        "weightmolar": -9.99,
                        "ohreact": -9.9e-09,
                        "vsetaver": -0.0003866022,
                        "spec_ass": -9,
                    },
                },
                "WD_spec001": {
                    "name": "WD_spec001",
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 40],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "Cs-137_wet_deposition",
                        "coordinates": "lon lat",
                        "weta": 7e-05,
                        "wetb": 0.8,
                        "dquer": 0.6,
                        "henry": 0.0,
                    },
                },
                "DD_spec001": {
                    "name": "DD_spec001",
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 40],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "Cs-137_dry_deposition",
                        "coordinates": "lon lat",
                        "dryvel": 0.0015,
                        "reldiff": -9.9,
                        "henry": 0.0,
                        "f0": 0.0,
                        "dquer": 0.6,
                        "density": 2500.0,
                        "dsigma": 0.3,
                    },
                },
                "fptot": {
                    "name": "fptot",
                    "dimensions": ["noutrel", "rlat", "rlon"],
                    "shape": [1, 30, 40],
                    "ncattrs": {
                        "coordinates": "lon lat",
                        "units": "ng kg-1",
                        "long_name": "total_footprint",
                        "sampling_height": "undefined",
                    },
                },
            },
            "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
        },
        "fld": {
            "dtype": "float32",
            "shape": [30, 40],
            "nanmin": 0.0,
            "nanmean": 9.7421966e-05,
            "nanmedian": 6.8192676e-06,
            "nanmax": 0.038744926,
            "nanmin_nonzero": 5.969089e-10,
            "nanmean_nonzero": 0.00016724801,
            "nanmedian_nonzero": 3.904104e-05,
            "nanmax_nonzero": 0.038744926,
            "n_nan": 0,
            "n_zero": 501,
        },
        "lat": {"dtype": "float32", "shape": [30], "min": -1.4000003, "max": 2.9499998},
        "lon": {"dtype": "float32", "shape": [40], "min": -1.7999997, "max": 4.0499997},
    },
    "fig": {
        "type": "Figure",
        "axes": [
            {
                "type": "GeoAxes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (0.0, 40.0, 984.0, 680.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (0.0, 736.0, 984.0, 64.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 680.0, 250.0, 120.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 392.0, 250.0, 272.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 40.0, 250.0, 336.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {"type": "TransformedBbox", "bounds": (0.0, 0.0, 1250.0, 40.0)},
            },
        ],
        "bbox": {"type": "TransformedBbox", "bounds": (0.0, 0.0, 1250.0, 800.0)},
    },
    "map_conf": {
        "type": "MapAxesConf",
        "geo_res": "10m",
        "geo_res_cities": "10m",
        "geo_res_rivers": "10m",
        "lang": "en",
        "lllat": None,
        "lllon": None,
        "lw_frame": 1.0,
        "min_city_pop": 0,
        "urlat": None,
        "urlon": None,
        "ref_dist_conf": {
            "type": "RefDistIndConf",
            "dist": 25,
            "font_size": 11.0,
            "pos": "bl",
            "unit": "km",
        },
        "ref_dist_on": True,
        "rel_offset": [-0.02, 0.045],
        "zoom_fact": 3.6,
    },
}
