# -*- coding: utf-8 -*-
# flake8: noqa
"""
Test reference for pytest test.

tests/slow/pyflexplot/test_plots/shared.py
    ::Test_Concentration
    ::test

Created by temporarily changing the parent class of
``Test_Concentration``
from ``_TestBase`` to ``_TestCreateReference`` and running pytest.
"""

field_summary = {
    "type": "Field",
    "rotated_pole": True,
    "var_setups": [
        {
            "infile": "flexpart_cosmo-1_2019093012.nc",
            "outfile": "dummy.png",
            "plot_type": "auto",
            "variable": "concentration",
            "deposition_type": "none",
            "integrate": False,
            "combine_species": False,
            "simulation_type": "deterministic",
            "ens_member_id": None,
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "lang": "de",
            "domain": "auto",
            "nageclass": [0],
            "noutrel": [0],
            "numpoint": [0],
            "species_id": [1],
            "time": [5],
            "level": [0],
        }
    ],
    "time_stats": {
        "mean": 2.9835212e-06,
        "median": 0.0,
        "mean_nz": 1.0435209e-05,
        "median_nz": 1.4416405e-06,
        "max": 0.0063348617,
    },
    "nc_meta_data": {
        "ncattrs": {"dxout": 0.01, "dyout": 0.01},
        "dimensions": {
            "time": {"name": "time", "size": 11},
            "rlon": {"name": "rlon", "size": 40},
            "rlat": {"name": "rlat", "size": 30},
            "level": {"name": "level", "size": 3},
            "numspec": {"name": "numspec", "size": 1},
            "numpoint": {"name": "numpoint", "size": 1},
            "noutrel": {"name": "noutrel", "size": 1},
            "nageclass": {"name": "nageclass", "size": 1},
            "nchar": {"name": "nchar", "size": 45},
        },
        "variables": {
            "time": {
                "name": "time",
                "dimensions": ["time"],
                "shape": [11],
                "ncattrs": {
                    "units": "seconds since 2019-09-30 12:00",
                    "calendar": "proleptic_gregorian",
                },
            },
            "rlon": {
                "name": "rlon",
                "dimensions": ["rlon"],
                "shape": [40],
                "ncattrs": {
                    "long_name": "longitude in rotated pole grid",
                    "units": "degrees",
                    "standard_name": "grid_longitude",
                    "axis": "X",
                    "description": "grid cell centers",
                },
            },
            "rlat": {
                "name": "rlat",
                "dimensions": ["rlat"],
                "shape": [30],
                "ncattrs": {
                    "long_name": "latitude in rotated pole grid",
                    "units": "degrees",
                    "standard_name": "grid_latitude",
                    "axis": "Y",
                    "description": "grid cell centers",
                },
            },
            "level": {
                "name": "level",
                "dimensions": ["level"],
                "shape": [3],
                "ncattrs": {
                    "axis": "Z",
                    "units": "meters",
                    "positive": "up",
                    "standard_name": "height",
                    "long_name": "height above ground",
                    "description": "grid cell top",
                },
            },
            "rotated_pole": {
                "name": "rotated_pole",
                "dimensions": {},
                "shape": {},
                "ncattrs": {
                    "grid_mapping_name": "rotated_latitude_longitude",
                    "grid_north_pole_latitude": 43.0,
                    "grid_north_pole_longitude": -170.0,
                },
            },
            "RELCOM": {
                "name": "RELCOM",
                "dimensions": ["numpoint", "nchar"],
                "shape": [1, 45],
                "ncattrs": {"long_name": "release point name"},
            },
            "RELLNG1": {
                "name": "RELLNG1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_east",
                    "long_name": "release longitude lower left corner",
                },
            },
            "RELLNG2": {
                "name": "RELLNG2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_east",
                    "long_name": "release longitude upper right corner",
                },
            },
            "RELLAT1": {
                "name": "RELLAT1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_north",
                    "long_name": "release latitude lower left corner",
                },
            },
            "RELLAT2": {
                "name": "RELLAT2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "degrees_north",
                    "long_name": "release latitude upper right corner",
                },
            },
            "RELZZ1": {
                "name": "RELZZ1",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"units": "meters", "long_name": "release height bottom"},
            },
            "RELZZ2": {
                "name": "RELZZ2",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"units": "meters", "long_name": "release height top"},
            },
            "RELKINDZ": {
                "name": "RELKINDZ",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"long_name": "release kind"},
            },
            "RELSTART": {
                "name": "RELSTART",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "seconds",
                    "long_name": "release start relative to simulation start",
                },
            },
            "RELEND": {
                "name": "RELEND",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {
                    "units": "seconds",
                    "long_name": "release end relative to simulation start",
                },
            },
            "RELPART": {
                "name": "RELPART",
                "dimensions": ["numpoint"],
                "shape": [1],
                "ncattrs": {"long_name": "number of release particles"},
            },
            "RELXMASS": {
                "name": "RELXMASS",
                "dimensions": ["numspec", "numpoint"],
                "shape": [1, 1],
                "ncattrs": {"long_name": "total release particle mass"},
            },
            "LAGE": {
                "name": "LAGE",
                "dimensions": ["nageclass"],
                "shape": [1],
                "ncattrs": {"units": "seconds", "long_name": "age class"},
            },
            "spec001": {
                "name": "spec001",
                "dimensions": ["nageclass", "noutrel", "time", "level", "rlat", "rlon"],
                "shape": [1, 1, 11, 3, 30, 40],
                "ncattrs": {
                    "units": "ng kg-1",
                    "long_name": "Cs-137",
                    "coordinates": "lon lat",
                    "decay": 7.3265155e-10,
                    "weightmolar": -9.99,
                    "ohreact": -9.9e-09,
                    "vsetaver": -0.0003866022,
                    "spec_ass": -9,
                },
            },
            "WD_spec001": {
                "name": "WD_spec001",
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 40],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "Cs-137_wet_deposition",
                    "coordinates": "lon lat",
                    "weta": 7e-05,
                    "wetb": 0.8,
                    "dquer": 0.6,
                    "henry": 0.0,
                },
            },
            "DD_spec001": {
                "name": "DD_spec001",
                "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                "shape": [1, 1, 11, 30, 40],
                "ncattrs": {
                    "units": "1e-12 kg m-2",
                    "long_name": "Cs-137_dry_deposition",
                    "coordinates": "lon lat",
                    "dryvel": 0.0015,
                    "reldiff": -9.9,
                    "henry": 0.0,
                    "f0": 0.0,
                    "dquer": 0.6,
                    "density": 2500.0,
                    "dsigma": 0.3,
                },
            },
            "fptot": {
                "name": "fptot",
                "dimensions": ["noutrel", "rlat", "rlon"],
                "shape": [1, 30, 40],
                "ncattrs": {
                    "coordinates": "lon lat",
                    "units": "ng kg-1",
                    "long_name": "total_footprint",
                    "sampling_height": "undefined",
                },
            },
        },
        "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
    },
    "fld": {
        "dtype": "float32",
        "shape": [30, 40],
        "nanmin": 0.0,
        "nanmean": 4.5633556e-06,
        "nanmedian": 0.0,
        "nanmax": 0.0010116174,
        "nanmin_nonzero": 2.310588e-10,
        "nanmean_nonzero": 1.0886733e-05,
        "nanmedian_nonzero": 1.6747575e-06,
        "nanmax_nonzero": 0.0010116174,
        "n_nan": 0,
        "n_zero": 697,
    },
    "lat": {"dtype": "float32", "shape": [30], "min": -1.4000003, "max": 2.9499998},
    "lon": {"dtype": "float32", "shape": [40], "min": -1.7999997, "max": 4.0499997},
}

plot_summary = {
    "type": "Plot",
    "ax_map": {"type": "MapAxesRotatedPole"},
    "boxes": {
        "top": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.0, 0.92, 0.7872, 0.08],
            "name": "top",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.009527439024390244,
            "dy_unit": 0.11250000000000004,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.009527439024390244,
                        "y0": 0.8875,
                        "x": 0.009527439024390244,
                        "y": 0.8875,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": 'Aktivit$\\mathrm{\\"a}$tskonzentration von Cs-137',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 14.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "bl",
                        "loc_y": "b",
                        "loc_x": "l",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.009527439024390244,
                        "y0": 0.11250000000000004,
                        "x": 0.009527439024390244,
                        "y": 0.11250000000000004,
                        "va": "baseline",
                        "ha": "left",
                    },
                    "s": 'Gemittelt $\\mathrm{\\"u}$ber 3:00$\\,$h seit +15:00$\\,$h',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "left",
                        "va": "baseline",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.9904725609756098,
                        "y0": 0.8875,
                        "x": 0.9904725609756098,
                        "y": 0.8875,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "2019-10-01 06:00 UTC (+18:00$\\,$h)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "br",
                        "loc_y": "b",
                        "loc_x": "r",
                        "dx_unit": 0.009527439024390244,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.9904725609756098,
                        "y0": 0.11250000000000004,
                        "x": 0.9904725609756098,
                        "y": 0.11250000000000004,
                        "va": "baseline",
                        "ha": "right",
                    },
                    "s": '18:00$\\,$h seit Freisetzungsbeginn in G$\\mathrm{\\"o}$sgen',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "right",
                        "va": "baseline",
                    },
                },
            ],
        },
        "right_top": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.8, 0.92, 0.2, 0.08],
            "name": "right_top",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.11250000000000004,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.8875,
                        "x": 0.037500000000000006,
                        "y": 0.8875,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Substanz:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.11250000000000004,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.9625,
                        "y0": 0.8875,
                        "x": 0.9625,
                        "y": 0.8875,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "Cs-137",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
            ],
        },
        "right_middle": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.8, 0.5, 0.2, 0.4],
            "name": "right_middle",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.022499999999999996,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.5,
                        "y": 0.9775,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Konzentration (Bq m$^{-3}$)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "center",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -5.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.8650000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-10 $\\tt -$ 1E-09",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -8.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.7975000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-09 $\\tt -$ 1E-08",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -11.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.7300000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-08 $\\tt -$ 1E-07",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -14.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.6625000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-07 $\\tt -$ 1E-06",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -17.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.5950000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-06 $\\tt -$ 1E-05",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -20.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.5275000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-05 $\\tt -$ 1E-04",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -23.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.4600000000000002,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "1E-04 $\\tt -$ 0.001",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -26.0,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.3925000000000002,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "      $\\tt \\geq$ 0.001",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "family": "monospace",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -6.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.8290000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "bisque",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -9.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.7615000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "violet",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -12.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.6940000000000002,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "rebeccapurple",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -15.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.6265000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "cornflowerblue",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -18.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.5590000000000002,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "yellowgreen",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -21.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.4915000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "greenyellow",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -24.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.42400000000000015,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "yellow",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementColorRect",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -10,
                        "dy": -27.6,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.12499999999999994,
                        "y": 0.35650000000000015,
                        "va": "top",
                        "ha": "center",
                    },
                    "w": 4.0,
                    "h": 2.0,
                    "fc": "lightgray",
                    "ec": "black",
                    "x_anker": "left",
                    "kwargs": {"lw": 1.0},
                },
                {
                    "type": "TextBoxElementMarker",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -8.0,
                        "dy": -30.400000000000002,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.19999999999999996,
                        "y": 0.2935000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "m": "^",
                    "kwargs": {
                        "markeredgecolor": "red",
                        "markerfacecolor": "white",
                        "markersize": 7.5,
                        "markeredgewidth": 1.5,
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -29.700000000000003,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.30925000000000014,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Abgabeort",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementMarker",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -8.0,
                        "dy": -33.400000000000006,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.19999999999999996,
                        "y": 0.2260000000000001,
                        "va": "top",
                        "ha": "center",
                    },
                    "m": "+",
                    "kwargs": {
                        "color": "black",
                        "markersize": 10,
                        "markeredgewidth": 1.5,
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.022499999999999996,
                        "dx": -3,
                        "dy": -32.7,
                        "x0": 0.5,
                        "y0": 0.9775,
                        "x": 0.38749999999999996,
                        "y": 0.24175000000000013,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Max.: 0.00101",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "ha": "left",
                        "fontname": "Liberation Sans",
                        "size": 10.0,
                        "va": "top",
                    },
                },
            ],
        },
        "right_bottom": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.8, 0.05, 0.2, 0.43],
            "name": "right_bottom",
            "lw_frame": 1.0,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.037500000000000006,
            "dy_unit": 0.020930232558139535,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tc",
                        "loc_y": "t",
                        "loc_x": "c",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": 0.0,
                        "x0": 0.5,
                        "y0": 0.9790697674418605,
                        "x": 0.5,
                        "y": 0.9790697674418605,
                        "va": "top",
                        "ha": "center",
                    },
                    "s": "Freisetzung",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 12.0,
                        "ha": "center",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -4.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.8953488372093024,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Ort:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -6.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.8430232558139534,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Breite:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -9.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.7906976744186047,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": 'L$\\mathrm{\\"a}$nge:',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -11.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.7383720930232558,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": 'H$\\mathrm{\\"o}$he:',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -16.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.6337209302325582,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Start:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -19.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.5813953488372093,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Ende:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -21.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.5290697674418605,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Rate:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -24.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.4767441860465116,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Totale Masse:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -29.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.37209302325581395,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Substanz:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -31.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.31976744186046513,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Halbwertszeit:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -34.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.2674418604651163,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Deposit.-Geschw.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -36.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.2151162790697675,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Sediment.-Geschw.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -39.0,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.16279069767441867,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Auswaschkoeff.:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -41.5,
                        "x0": 0.037500000000000006,
                        "y0": 0.9790697674418605,
                        "x": 0.037500000000000006,
                        "y": 0.11046511627906974,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "Auswaschexponent:",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -4.0,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.8953488372093024,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": 'G$\\mathrm{\\"o}$sgen',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -6.5,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.8430232558139534,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "47$^\\circ$$\\,$21'$\\,$N (47.3659$^\\circ$$\\,$N)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -9.0,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.7906976744186047,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "7$^\\circ$$\\,$58'$\\,$O (7.9668$^\\circ$$\\,$O)",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -11.5,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.7383720930232558,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": '100$\\,$m $\\mathrm{\\"u}$.G.',
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -16.5,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.6337209302325582,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "2019-09-30 12:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -19.0,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.5813953488372093,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "2019-09-30 20:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -21.5,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.5290697674418605,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "34722.2$\\,$Bq s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -24.0,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.4767441860465116,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "1e+09$\\,$Bq",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -29.0,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.37209302325581395,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "Cs-137",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -31.5,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.31976744186046513,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "30.17$\\,$a",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -34.0,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.2674418604651163,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "0.0015$\\,$m s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -36.5,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.2151162790697675,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "0$\\,$m s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -39.0,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.16279069767441867,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "7e-05$\\,$s$^{-1}$",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.037500000000000006,
                        "dy_unit": 0.020930232558139535,
                        "dx": 0.0,
                        "dy": -41.5,
                        "x0": 0.9625,
                        "y0": 0.9790697674418605,
                        "x": 0.9625,
                        "y": 0.11046511627906974,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "0.8",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
            ],
        },
        "bottom": {
            "type": "TextBoxAxes",
            "fig": {
                "type": "Figure",
                "axes": {"type": "bbox"},
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": [0.0, 0.0, 1250.0, 800.0],
                },
            },
            "rect": [0.0, 0.0, 1.0, 0.05],
            "name": "bottom",
            "lw_frame": None,
            "ec": "black",
            "fc": "none",
            "show_baselines": False,
            "dx_unit": 0.0075,
            "dy_unit": 0.17999999999999997,
            "elements": [
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tl",
                        "loc_y": "t",
                        "loc_x": "l",
                        "dx_unit": 0.0075,
                        "dy_unit": 0.17999999999999997,
                        "dx": -0.7,
                        "dy": 0.5,
                        "x0": 0.0075,
                        "y0": 0.8200000000000001,
                        "x": 0.0022500000000000003,
                        "y": 0.91,
                        "va": "top",
                        "ha": "left",
                    },
                    "s": "FLEXPART basierend auf COSMO-1, 2019-09-30 12:00 UTC",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "left",
                        "va": "top",
                    },
                },
                {
                    "type": "TextBoxElementText",
                    "loc": {
                        "type": "TextBoxLocation",
                        "loc": "tr",
                        "loc_y": "t",
                        "loc_x": "r",
                        "dx_unit": 0.0075,
                        "dy_unit": 0.17999999999999997,
                        "dx": 0.7,
                        "dy": 0.5,
                        "x0": 0.9925,
                        "y0": 0.8200000000000001,
                        "x": 0.99775,
                        "y": 0.91,
                        "va": "top",
                        "ha": "right",
                    },
                    "s": "©MeteoSchweiz",
                    "replace_edge_spaces": False,
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "fontname": "Liberation Sans",
                        "size": 9.0,
                        "ha": "right",
                        "va": "top",
                    },
                },
            ],
        },
    },
    "field": {
        "type": "Field",
        "rotated_pole": True,
        "var_setups": [
            {
                "infile": "flexpart_cosmo-1_2019093012.nc",
                "outfile": "dummy.png",
                "plot_type": "auto",
                "variable": "concentration",
                "deposition_type": "none",
                "integrate": False,
                "combine_species": False,
                "simulation_type": "deterministic",
                "ens_member_id": None,
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "lang": "de",
                "domain": "auto",
                "nageclass": [0],
                "noutrel": [0],
                "numpoint": [0],
                "species_id": [1],
                "time": [5],
                "level": [0],
            }
        ],
        "time_stats": {
            "mean": 2.9835212e-06,
            "median": 0.0,
            "mean_nz": 1.0435209e-05,
            "median_nz": 1.4416405e-06,
            "max": 0.0063348617,
        },
        "nc_meta_data": {
            "ncattrs": {"dxout": 0.01, "dyout": 0.01},
            "dimensions": {
                "time": {"name": "time", "size": 11},
                "rlon": {"name": "rlon", "size": 40},
                "rlat": {"name": "rlat", "size": 30},
                "level": {"name": "level", "size": 3},
                "numspec": {"name": "numspec", "size": 1},
                "numpoint": {"name": "numpoint", "size": 1},
                "noutrel": {"name": "noutrel", "size": 1},
                "nageclass": {"name": "nageclass", "size": 1},
                "nchar": {"name": "nchar", "size": 45},
            },
            "variables": {
                "time": {
                    "name": "time",
                    "dimensions": ["time"],
                    "shape": [11],
                    "ncattrs": {
                        "units": "seconds since 2019-09-30 12:00",
                        "calendar": "proleptic_gregorian",
                    },
                },
                "rlon": {
                    "name": "rlon",
                    "dimensions": ["rlon"],
                    "shape": [40],
                    "ncattrs": {
                        "long_name": "longitude in rotated pole grid",
                        "units": "degrees",
                        "standard_name": "grid_longitude",
                        "axis": "X",
                        "description": "grid cell centers",
                    },
                },
                "rlat": {
                    "name": "rlat",
                    "dimensions": ["rlat"],
                    "shape": [30],
                    "ncattrs": {
                        "long_name": "latitude in rotated pole grid",
                        "units": "degrees",
                        "standard_name": "grid_latitude",
                        "axis": "Y",
                        "description": "grid cell centers",
                    },
                },
                "level": {
                    "name": "level",
                    "dimensions": ["level"],
                    "shape": [3],
                    "ncattrs": {
                        "axis": "Z",
                        "units": "meters",
                        "positive": "up",
                        "standard_name": "height",
                        "long_name": "height above ground",
                        "description": "grid cell top",
                    },
                },
                "rotated_pole": {
                    "name": "rotated_pole",
                    "dimensions": {},
                    "shape": {},
                    "ncattrs": {
                        "grid_mapping_name": "rotated_latitude_longitude",
                        "grid_north_pole_latitude": 43.0,
                        "grid_north_pole_longitude": -170.0,
                    },
                },
                "RELCOM": {
                    "name": "RELCOM",
                    "dimensions": ["numpoint", "nchar"],
                    "shape": [1, 45],
                    "ncattrs": {"long_name": "release point name"},
                },
                "RELLNG1": {
                    "name": "RELLNG1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_east",
                        "long_name": "release longitude lower left corner",
                    },
                },
                "RELLNG2": {
                    "name": "RELLNG2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_east",
                        "long_name": "release longitude upper right corner",
                    },
                },
                "RELLAT1": {
                    "name": "RELLAT1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_north",
                        "long_name": "release latitude lower left corner",
                    },
                },
                "RELLAT2": {
                    "name": "RELLAT2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "degrees_north",
                        "long_name": "release latitude upper right corner",
                    },
                },
                "RELZZ1": {
                    "name": "RELZZ1",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "meters",
                        "long_name": "release height bottom",
                    },
                },
                "RELZZ2": {
                    "name": "RELZZ2",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"units": "meters", "long_name": "release height top"},
                },
                "RELKINDZ": {
                    "name": "RELKINDZ",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"long_name": "release kind"},
                },
                "RELSTART": {
                    "name": "RELSTART",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "seconds",
                        "long_name": "release start relative to simulation start",
                    },
                },
                "RELEND": {
                    "name": "RELEND",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {
                        "units": "seconds",
                        "long_name": "release end relative to simulation start",
                    },
                },
                "RELPART": {
                    "name": "RELPART",
                    "dimensions": ["numpoint"],
                    "shape": [1],
                    "ncattrs": {"long_name": "number of release particles"},
                },
                "RELXMASS": {
                    "name": "RELXMASS",
                    "dimensions": ["numspec", "numpoint"],
                    "shape": [1, 1],
                    "ncattrs": {"long_name": "total release particle mass"},
                },
                "LAGE": {
                    "name": "LAGE",
                    "dimensions": ["nageclass"],
                    "shape": [1],
                    "ncattrs": {"units": "seconds", "long_name": "age class"},
                },
                "spec001": {
                    "name": "spec001",
                    "dimensions": [
                        "nageclass",
                        "noutrel",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "shape": [1, 1, 11, 3, 30, 40],
                    "ncattrs": {
                        "units": "ng kg-1",
                        "long_name": "Cs-137",
                        "coordinates": "lon lat",
                        "decay": 7.3265155e-10,
                        "weightmolar": -9.99,
                        "ohreact": -9.9e-09,
                        "vsetaver": -0.0003866022,
                        "spec_ass": -9,
                    },
                },
                "WD_spec001": {
                    "name": "WD_spec001",
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 40],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "Cs-137_wet_deposition",
                        "coordinates": "lon lat",
                        "weta": 7e-05,
                        "wetb": 0.8,
                        "dquer": 0.6,
                        "henry": 0.0,
                    },
                },
                "DD_spec001": {
                    "name": "DD_spec001",
                    "dimensions": ["nageclass", "noutrel", "time", "rlat", "rlon"],
                    "shape": [1, 1, 11, 30, 40],
                    "ncattrs": {
                        "units": "1e-12 kg m-2",
                        "long_name": "Cs-137_dry_deposition",
                        "coordinates": "lon lat",
                        "dryvel": 0.0015,
                        "reldiff": -9.9,
                        "henry": 0.0,
                        "f0": 0.0,
                        "dquer": 0.6,
                        "density": 2500.0,
                        "dsigma": 0.3,
                    },
                },
                "fptot": {
                    "name": "fptot",
                    "dimensions": ["noutrel", "rlat", "rlon"],
                    "shape": [1, 30, 40],
                    "ncattrs": {
                        "coordinates": "lon lat",
                        "units": "ng kg-1",
                        "long_name": "total_footprint",
                        "sampling_height": "undefined",
                    },
                },
            },
            "analysis": {"model": "cosmo1", "rotated_pole": True, "species_ids": [1]},
        },
        "fld": {
            "dtype": "float32",
            "shape": [30, 40],
            "nanmin": 0.0,
            "nanmean": 4.5633556e-06,
            "nanmedian": 0.0,
            "nanmax": 0.0010116174,
            "nanmin_nonzero": 2.310588e-10,
            "nanmean_nonzero": 1.0886733e-05,
            "nanmedian_nonzero": 1.6747575e-06,
            "nanmax_nonzero": 0.0010116174,
            "n_nan": 0,
            "n_zero": 697,
        },
        "lat": {"dtype": "float32", "shape": [30], "min": -1.4000003, "max": 2.9499998},
        "lon": {"dtype": "float32", "shape": [40], "min": -1.7999997, "max": 4.0499997},
    },
    "fig": {
        "type": "Figure",
        "axes": [
            {
                "type": "GeoAxes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (0.0, 40.0, 984.0, 680.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (0.0, 736.0, 984.0, 64.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 736.0, 250.0, 64.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 400.0, 250.0, 320.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {
                    "type": "TransformedBbox",
                    "bounds": (1000.0, 40.0, 250.0, 344.0),
                },
            },
            {
                "type": "Axes",
                "bbox": {"type": "TransformedBbox", "bounds": (0.0, 0.0, 1250.0, 40.0)},
            },
        ],
        "bbox": {"type": "TransformedBbox", "bounds": (0.0, 0.0, 1250.0, 800.0)},
    },
    "map_conf": {
        "type": "MapAxesConf",
        "geo_res": "10m",
        "geo_res_cities": "50m",
        "geo_res_rivers": "50m",
        "lang": "de",
        "lllat": None,
        "lllon": None,
        "lw_frame": 1.0,
        "min_city_pop": 300000,
        "urlat": None,
        "urlon": None,
        "ref_dist_conf": {
            "type": "RefDistIndConf",
            "dist": 100,
            "font_size": 11.0,
            "pos": "bl",
            "unit": "km",
        },
        "ref_dist_on": True,
        "rel_offset": [0.0, 0.0],
        "zoom_fact": 1.02,
    },
}
