# -*- coding: utf-8 -*-
"""
Test reference for pytest test.

tests/slow/pyflexplot/test_plots/shared.py::Test_EnsMedian_Concentration::test

Created by temporarily changing the parent class of ``Test_EnsMedian_Concentration``
from ``_TestBase`` to ``_CreateReference`` and running pytest.
"""

field_summary = {
    "fld": {
        "dtype": "float32",
        "n_nan": 0,
        "n_zero": 1473,
        "nanmax": 0.0011326676,
        "nanmax_nonzero": 0.0011326676,
        "nanmean": 2.5434304e-06,
        "nanmean_nonzero": 0.00014130169,
        "nanmedian": 0.0,
        "nanmedian_nonzero": 2.0320085e-05,
        "nanmin": 0.0,
        "nanmin_nonzero": 3.2904253e-09,
        "shape": (30, 50),
    },
    "lat": {"dtype": "float32", "max": -0.42000008, "min": -3.3199997, "shape": (30,)},
    "lon": {"dtype": "float32", "max": 2.4799995, "min": -2.42, "shape": (50,)},
    "nc_meta_data": {
        "analysis": {"model": "cosmo2", "rotated_pole": True, "species_ids": [1, 2]},
        "dimensions": {
            "level": {"name": "level", "size": 3},
            "nageclass": {"name": "nageclass", "size": 1},
            "nchar": {"name": "nchar", "size": 45},
            "numpoint": {"name": "numpoint", "size": 1},
            "numspec": {"name": "numspec", "size": 2},
            "rlat": {"name": "rlat", "size": 30},
            "rlon": {"name": "rlon", "size": 50},
            "time": {"name": "time", "size": 11},
        },
        "ncattrs": {"dxout": 0.02, "dyout": 0.02},
        "variables": {
            "DD_spec001": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "DD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "density": 2500.0,
                    "dquer": 0.6,
                    "dryvel": 0.0015,
                    "dsigma": 0.3,
                    "f0": 0.0,
                    "henry": 0.0,
                    "long_name": "Cs-137_dry_deposition",
                    "reldiff": -9.9,
                    "units": "1e-12 kg " "m-2",
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "DD_spec002": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "DD_spec002",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "density": 2500.0,
                    "dquer": 0.6,
                    "dryvel": 0.0015,
                    "dsigma": 0.3,
                    "f0": 0.0,
                    "henry": 0.0,
                    "long_name": "I-131a_dry_deposition",
                    "reldiff": -9.9,
                    "units": "1e-12 kg " "m-2",
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "LAGE": {
                "dimensions": ["nageclass"],
                "name": "LAGE",
                "ncattrs": {"long_name": "age class", "units": "seconds"},
                "shape": [1],
            },
            "RELCOM": {
                "dimensions": ["numpoint", "nchar"],
                "name": "RELCOM",
                "ncattrs": {"long_name": "release " "point " "name"},
                "shape": [1, 45],
            },
            "RELEND": {
                "dimensions": ["numpoint"],
                "name": "RELEND",
                "ncattrs": {
                    "long_name": "release "
                    "end "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELKINDZ": {
                "dimensions": ["numpoint"],
                "name": "RELKINDZ",
                "ncattrs": {"long_name": "release " "kind"},
                "shape": [1],
            },
            "RELLAT1": {
                "dimensions": ["numpoint"],
                "name": "RELLAT1",
                "ncattrs": {
                    "long_name": "release " "latitude " "lower " "left " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLAT2": {
                "dimensions": ["numpoint"],
                "name": "RELLAT2",
                "ncattrs": {
                    "long_name": "release " "latitude " "upper " "right " "corner",
                    "units": "degrees_north",
                },
                "shape": [1],
            },
            "RELLNG1": {
                "dimensions": ["numpoint"],
                "name": "RELLNG1",
                "ncattrs": {
                    "long_name": "release " "longitude " "lower " "left " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELLNG2": {
                "dimensions": ["numpoint"],
                "name": "RELLNG2",
                "ncattrs": {
                    "long_name": "release " "longitude " "upper " "right " "corner",
                    "units": "degrees_east",
                },
                "shape": [1],
            },
            "RELPART": {
                "dimensions": ["numpoint"],
                "name": "RELPART",
                "ncattrs": {"long_name": "number " "of " "release " "particles"},
                "shape": [1],
            },
            "RELSTART": {
                "dimensions": ["numpoint"],
                "name": "RELSTART",
                "ncattrs": {
                    "long_name": "release "
                    "start "
                    "relative "
                    "to "
                    "simulation "
                    "start",
                    "units": "seconds",
                },
                "shape": [1],
            },
            "RELXMASS": {
                "dimensions": ["numspec", "numpoint"],
                "name": "RELXMASS",
                "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                "shape": [2, 1],
            },
            "RELZZ1": {
                "dimensions": ["numpoint"],
                "name": "RELZZ1",
                "ncattrs": {
                    "long_name": "release " "height " "bottom",
                    "units": "meters",
                },
                "shape": [1],
            },
            "RELZZ2": {
                "dimensions": ["numpoint"],
                "name": "RELZZ2",
                "ncattrs": {"long_name": "release " "height " "top", "units": "meters"},
                "shape": [1],
            },
            "WD_spec001": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "WD_spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "dquer": 0.6,
                    "henry": 0.0,
                    "long_name": "Cs-137_wet_deposition",
                    "units": "1e-12 kg " "m-2",
                    "weta": 7e-05,
                    "wetb": 0.8,
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "WD_spec002": {
                "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                "name": "WD_spec002",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "dquer": 0.6,
                    "henry": 0.0,
                    "long_name": "I-131a_wet_deposition",
                    "units": "1e-12 kg " "m-2",
                    "weta": 7e-05,
                    "wetb": 0.8,
                },
                "shape": [1, 1, 11, 30, 50],
            },
            "fptot": {
                "dimensions": ["numpoint", "rlat", "rlon"],
                "name": "fptot",
                "ncattrs": {
                    "coordinates": "lon lat",
                    "long_name": "total_footprint",
                    "sampling_height": "undefined",
                    "units": "ng kg-1",
                },
                "shape": [1, 30, 50],
            },
            "level": {
                "dimensions": ["level"],
                "name": "level",
                "ncattrs": {
                    "axis": "Z",
                    "description": "grid " "cell top",
                    "long_name": "height " "above " "ground",
                    "positive": "up",
                    "standard_name": "height",
                    "units": "meters",
                },
                "shape": [3],
            },
            "rlat": {
                "dimensions": ["rlat"],
                "name": "rlat",
                "ncattrs": {
                    "axis": "Y",
                    "description": "grid cell " "centers",
                    "long_name": "latitude in " "rotated " "pole grid",
                    "standard_name": "grid_latitude",
                    "units": "degrees",
                },
                "shape": [30],
            },
            "rlon": {
                "dimensions": ["rlon"],
                "name": "rlon",
                "ncattrs": {
                    "axis": "X",
                    "description": "grid cell " "centers",
                    "long_name": "longitude " "in rotated " "pole grid",
                    "standard_name": "grid_longitude",
                    "units": "degrees",
                },
                "shape": [50],
            },
            "rotated_pole": {
                "dimensions": {},
                "name": "rotated_pole",
                "ncattrs": {
                    "grid_mapping_name": "rotated_latitude_longitude",
                    "grid_north_pole_latitude": 43.0,
                    "grid_north_pole_longitude": -170.0,
                },
                "shape": {},
            },
            "spec001": {
                "dimensions": [
                    "nageclass",
                    "numpoint",
                    "time",
                    "level",
                    "rlat",
                    "rlon",
                ],
                "name": "spec001",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "decay": 7.3265155e-10,
                    "long_name": "Cs-137",
                    "ohreact": -9.9e-09,
                    "spec_ass": -9,
                    "units": "ng kg-1",
                    "vsetaver": -0.0003866022,
                    "weightmolar": -9.99,
                },
                "shape": [1, 1, 11, 3, 30, 50],
            },
            "spec002": {
                "dimensions": [
                    "nageclass",
                    "numpoint",
                    "time",
                    "level",
                    "rlat",
                    "rlon",
                ],
                "name": "spec002",
                "ncattrs": {
                    "coordinates": "lon " "lat",
                    "decay": 9.978277e-07,
                    "long_name": "I-131a",
                    "ohreact": -9.9e-09,
                    "spec_ass": -9,
                    "units": "ng kg-1",
                    "vsetaver": -0.0003866022,
                    "weightmolar": -9.99,
                },
                "shape": [1, 1, 11, 3, 30, 50],
            },
            "time": {
                "dimensions": ["time"],
                "name": "time",
                "ncattrs": {
                    "calendar": "proleptic_gregorian",
                    "units": "seconds since " "2019-07-27 " "12:00",
                },
                "shape": [11],
            },
        },
    },
    "rotated_pole": True,
    "time_stats": {
        "max": 0.0023557064,
        "mean": 4.0843393e-06,
        "mean_nz": 2.9338966e-05,
        "median": 0.0,
        "median_nz": 3.3051265e-06,
    },
    "type": "Field",
    "var_setups": [
        {
            "combine_species": True,
            "deposition_type": "none",
            "domain": "auto",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "integrate": False,
            "lang": "de",
            "level": [0],
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "outfile": "dummy.png",
            "plot_type": "ens_median",
            "simulation_type": "ensemble",
            "species_id": [1],
            "time": [5],
            "variable": "concentration",
        },
        {
            "combine_species": True,
            "deposition_type": "none",
            "domain": "auto",
            "ens_member_id": [0, 1, 5, 10, 15, 20],
            "ens_param_mem_min": None,
            "ens_param_thr": None,
            "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
            "integrate": False,
            "lang": "de",
            "level": [0],
            "nageclass": [0],
            "noutrel": None,
            "numpoint": [0],
            "outfile": "dummy.png",
            "plot_type": "ens_median",
            "simulation_type": "ensemble",
            "species_id": [2],
            "time": [5],
            "variable": "concentration",
        },
    ],
}

plot_summary = {
    "ax_map": {"type": "MapAxesRotatedPole"},
    "boxes": {
        "method:Plot.fill_box_bottom": {
            "dx_unit": 0.00790513833992095,
            "dy_unit": 0.42357852021844894,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "small", "va": "top"},
                    "loc": {
                        "dx": -0.7,
                        "dx_unit": 0.00790513833992095,
                        "dy": 0.5,
                        "dy_unit": 0.42357852021844894,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.003952569169960475,
                        "x0": 0.009486166007905139,
                        "y": 0.7034950358470858,
                        "y0": 0.49170577573786134,
                    },
                    "replace_edge_spaces": False,
                    "s": "FLEXPART "
                    "basierend auf "
                    "COSMO-2, "
                    "2019-07-27 "
                    "12:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "small", "va": "top"},
                    "loc": {
                        "dx": 0.7,
                        "dx_unit": 0.00790513833992095,
                        "dy": 0.5,
                        "dy_unit": 0.42357852021844894,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.9960474308300395,
                        "x0": 0.9905138339920949,
                        "y": 0.7034950358470858,
                        "y0": 0.49170577573786134,
                    },
                    "replace_edge_spaces": False,
                    "s": "©MeteoSchweiz",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": None,
            "name": "bottom",
            "rect": [0.05, 0.03170351037629776, 0.980375, 0.01829648962370224],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_bottom": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.024099246863515326,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": -1.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.9469816569002664,
                        "y0": 0.9710809037637816,
                    },
                    "replace_edge_spaces": False,
                    "s": "Freisetzung",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.06506796653149138,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschexponent:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 4.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.1253160836902797,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Auswaschkoeff.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 6.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.185564200849068,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Sediment.-Geschw.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 9.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.24581231800785633,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Deposit.-Geschw.:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 11.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.30606043516664466,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Halbwertszeit:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 14.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.36630855232543297,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Substanz:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.48680478664300963,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Totale " "Masse:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 21.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.5470529038017978,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Rate:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 24.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.6073010209605861,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ende:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 26.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.6675491381193746,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Start:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.7880453724369512,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": 'H$\\mathrm{\\"o}$he:',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 34.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.8482934895957395,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": 'L$\\mathrm{\\"a}$nge:',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 36.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.9085416067545278,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Breite:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "left",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 39.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.048000000000000015,
                        "x0": 0.048000000000000015,
                        "y": 0.9687897239133161,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort:",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.06506796653149138,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 4.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.1253160836902797,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 6.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.185564200849068,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 9.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.24581231800785633,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "0",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 11.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.30606043516664466,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "30 / 8",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 14.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.36630855232543297,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137 + " "I-131a",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 19.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.48680478664300963,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "1e+09",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 21.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.5470529038017978,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "34722",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 24.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.6073010209605861,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-07-27 " "20:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 26.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.6675491381193746,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-07-27 " "12:00 UTC",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 31.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.7880453724369512,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "100",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 34.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.8482934895957395,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "7$^\\circ$$\\,$0'$\\,$O " "(7.0000$^\\circ$$\\,$O)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 36.5,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.9085416067545278,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": "47$^\\circ$$\\,$0'$\\,$N " "(47.0000$^\\circ$$\\,$N)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "ha": "right",
                        "size": "small",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 39.0,
                        "dy_unit": 0.024099246863515326,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.952,
                        "x0": 0.952,
                        "y": 0.9687897239133161,
                        "y0": 0.02891909623621839,
                    },
                    "replace_edge_spaces": False,
                    "s": 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/bottom",
            "rect": [0.8366250000000001, 0.05, 0.19375, 0.32158681322664034],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_right_top": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.028409489326133103,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 1.5,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 1.00852284679784,
                        "y0": 0.9659086128086403,
                    },
                    "replace_edge_spaces": False,
                    "s": "Konzentration " "(Bq m-3)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 9.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.28977679112655763,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-10 $\\tt " "-$ 1E-09",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 12.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.37500525910495697,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-09 $\\tt " "-$ 1E-08",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 15.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.4602337270833563,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-08 $\\tt " "-$ 1E-07",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 18.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.5454621950617555,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-07 $\\tt " "-$ 1E-06",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 21.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.6306906630401549,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-06 $\\tt " "-$ 1E-05",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 24.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.7159191310185542,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-05 $\\tt " "-$ 1E-04",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 27.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.8011475989969535,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "1E-04 $\\tt " "-$ 0.001",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {
                        "color": "black",
                        "family": "monospace",
                        "ha": "left",
                        "size": "medium",
                        "va": "baseline",
                    },
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 30.0,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.8863760669753529,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "      $\\tt " "\\geq$ 0.001",
                    "type": "TextBoxElementText",
                },
                {
                    "ec": "black",
                    "fc": [0.8784313725490196, 0.7686274509803922, 0.6745098039215687],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 8.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.27841299539610437,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.8666666666666667, 0.4980392156862745, 0.8431372549019608],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 11.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.3636414633745037,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.38823529411764707, 0.0, 1.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 14.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.44886993135290304,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.39215686274509803, 0.6, 0.7803921568627451],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 17.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.5340983993313024,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.36470588235294116, 1.0, 0.00784313725490196],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 20.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.6193268673097017,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7803921568627451, 1.0, 0.0],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 23.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.704555335288101,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [1.0, 0.9372549019607843, 0.2235294117647059],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 26.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.7897838032665003,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "ec": "black",
                    "fc": [0.7843137254901961, 0.7843137254901961, 0.7843137254901961],
                    "h": 2.0,
                    "kwargs": {"lw": 1.0},
                    "loc": {
                        "dx": -10,
                        "dx_unit": 0.040000000000000015,
                        "dy": 29.6,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.09999999999999987,
                        "x0": 0.5,
                        "y": 0.8750122712448997,
                        "y0": 0.03409138719135972,
                    },
                    "type": "TextBoxElementColorRect",
                    "w": 4.0,
                    "x_anker": "left",
                },
                {
                    "kwargs": {
                        "markeredgecolor": "red",
                        "markeredgewidth": 1.5,
                        "markerfacecolor": "white",
                        "markersize": 7.5,
                    },
                    "loc": {
                        "dx": -8.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.95,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.17999999999999988,
                        "x0": 0.5,
                        "y": 0.061080402051186165,
                        "y0": 0.03409138719135972,
                    },
                    "m": "^",
                    "type": "TextBoxElementMarker",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.25,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.041193759522892996,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "Abgabeort",
                    "type": "TextBoxElementText",
                },
                {
                    "kwargs": {
                        "color": "black",
                        "markeredgewidth": 1.5,
                        "markersize": 10,
                    },
                    "loc": {
                        "dx": -8.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 3.95,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.17999999999999988,
                        "x0": 0.5,
                        "y": 0.14630887002958548,
                        "y0": 0.03409138719135972,
                    },
                    "m": "+",
                    "type": "TextBoxElementMarker",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "medium", "va": "baseline"},
                    "loc": {
                        "dx": -3,
                        "dx_unit": 0.040000000000000015,
                        "dy": 3.25,
                        "dy_unit": 0.028409489326133103,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.37999999999999995,
                        "x0": 0.5,
                        "y": 0.12642222750129228,
                        "y0": 0.03409138719135972,
                    },
                    "replace_edge_spaces": False,
                    "s": "Max.: " "0.00113",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "right/top",
            "rect": [
                0.8366250000000001,
                0.38708681322664035,
                0.19375,
                0.27279617423010105,
            ],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_left": {
            "dx_unit": 0.01,
            "dy_unit": 0.0907668257610962,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.0907668257610962,
                        "ha": "left",
                        "loc": "tl",
                        "loc_x": "l",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.012,
                        "x0": 0.012,
                        "y": 0.8910798090866846,
                        "y0": 0.8910798090866846,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ensemble-Median "
                    "Konzentration "
                    "auf 0$-$500 m "
                    '$\\mathrm{\\"u}$.G.',
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "left", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.0907668257610962,
                        "ha": "left",
                        "loc": "bl",
                        "loc_x": "l",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.012,
                        "x0": 0.012,
                        "y": 0.10892019091331544,
                        "y0": 0.10892019091331544,
                    },
                    "replace_edge_spaces": False,
                    "s": "Gemittelt "
                    '$\\mathrm{\\"u}$ber '
                    "3$\\,$h (seit "
                    "+15:00$\\,$h)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.0907668257610962,
                        "ha": "right",
                        "loc": "tr",
                        "loc_x": "r",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.988,
                        "x0": 0.988,
                        "y": 0.8910798090866846,
                        "y0": 0.8910798090866846,
                    },
                    "replace_edge_spaces": False,
                    "s": "2019-07-28 " "06:00 UTC " "(+18:00$\\,$h)",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "right", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.01,
                        "dy": 0.0,
                        "dy_unit": 0.0907668257610962,
                        "ha": "right",
                        "loc": "br",
                        "loc_x": "r",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.988,
                        "x0": 0.988,
                        "y": 0.10892019091331544,
                        "y0": 0.10892019091331544,
                    },
                    "replace_edge_spaces": False,
                    "s": "18:00$\\,$h " "seit " "Freisetzungsbeginn",
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/left",
            "rect": [0.05, 0.6753829874567413, 0.775, 0.08538361824394379],
            "type": "TextBoxAxes",
        },
        "method:Plot.fill_box_top_right": {
            "dx_unit": 0.040000000000000015,
            "dy_unit": 0.0907668257610962,
            "elements": [
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "top"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.0,
                        "dy_unit": 0.0907668257610962,
                        "ha": "center",
                        "loc": "tc",
                        "loc_x": "c",
                        "loc_y": "t",
                        "type": "TextBoxLocation",
                        "va": "top",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.8910798090866846,
                        "y0": 0.8910798090866846,
                    },
                    "replace_edge_spaces": False,
                    "s": "Cs-137 + " "I-131a",
                    "type": "TextBoxElementText",
                },
                {
                    "edge_spaces_replacement_char": "␣",
                    "kwargs": {"ha": "center", "size": "large", "va": "baseline"},
                    "loc": {
                        "dx": 0.0,
                        "dx_unit": 0.040000000000000015,
                        "dy": 0.0,
                        "dy_unit": 0.0907668257610962,
                        "ha": "center",
                        "loc": "bc",
                        "loc_x": "c",
                        "loc_y": "b",
                        "type": "TextBoxLocation",
                        "va": "baseline",
                        "x": 0.5,
                        "x0": 0.5,
                        "y": 0.10892019091331544,
                        "y0": 0.10892019091331544,
                    },
                    "replace_edge_spaces": False,
                    "s": "Ort: " 'G$\\mathrm{\\"o}$sgen',
                    "type": "TextBoxElementText",
                },
            ],
            "lw_frame": 1.0,
            "name": "top/right",
            "rect": [
                0.8366250000000001,
                0.6753829874567413,
                0.19375,
                0.08538361824394379,
            ],
            "type": "TextBoxAxes",
        },
    },
    "draw_colors": True,
    "draw_contours": False,
    "field": {
        "fld": {
            "dtype": "float32",
            "n_nan": 0,
            "n_zero": 1473,
            "nanmax": 0.0011326676,
            "nanmax_nonzero": 0.0011326676,
            "nanmean": 2.5434304e-06,
            "nanmean_nonzero": 0.00014130169,
            "nanmedian": 0.0,
            "nanmedian_nonzero": 2.0320085e-05,
            "nanmin": 0.0,
            "nanmin_nonzero": 3.2904253e-09,
            "shape": [30, 50],
        },
        "lat": {
            "dtype": "float32",
            "max": -0.42000008,
            "min": -3.3199997,
            "shape": [30],
        },
        "lon": {"dtype": "float32", "max": 2.4799995, "min": -2.42, "shape": [50]},
        "nc_meta_data": {
            "analysis": {
                "model": "cosmo2",
                "rotated_pole": True,
                "species_ids": [1, 2],
            },
            "dimensions": {
                "level": {"name": "level", "size": 3},
                "nageclass": {"name": "nageclass", "size": 1},
                "nchar": {"name": "nchar", "size": 45},
                "numpoint": {"name": "numpoint", "size": 1},
                "numspec": {"name": "numspec", "size": 2},
                "rlat": {"name": "rlat", "size": 30},
                "rlon": {"name": "rlon", "size": 50},
                "time": {"name": "time", "size": 11},
            },
            "ncattrs": {"dxout": 0.02, "dyout": 0.02},
            "variables": {
                "DD_spec001": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "DD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "density": 2500.0,
                        "dquer": 0.6,
                        "dryvel": 0.0015,
                        "dsigma": 0.3,
                        "f0": 0.0,
                        "henry": 0.0,
                        "long_name": "Cs-137_dry_deposition",
                        "reldiff": -9.9,
                        "units": "1e-12 " "kg " "m-2",
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "DD_spec002": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "DD_spec002",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "density": 2500.0,
                        "dquer": 0.6,
                        "dryvel": 0.0015,
                        "dsigma": 0.3,
                        "f0": 0.0,
                        "henry": 0.0,
                        "long_name": "I-131a_dry_deposition",
                        "reldiff": -9.9,
                        "units": "1e-12 " "kg " "m-2",
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "LAGE": {
                    "dimensions": ["nageclass"],
                    "name": "LAGE",
                    "ncattrs": {"long_name": "age " "class", "units": "seconds"},
                    "shape": [1],
                },
                "RELCOM": {
                    "dimensions": ["numpoint", "nchar"],
                    "name": "RELCOM",
                    "ncattrs": {"long_name": "release " "point " "name"},
                    "shape": [1, 45],
                },
                "RELEND": {
                    "dimensions": ["numpoint"],
                    "name": "RELEND",
                    "ncattrs": {
                        "long_name": "release "
                        "end "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELKINDZ": {
                    "dimensions": ["numpoint"],
                    "name": "RELKINDZ",
                    "ncattrs": {"long_name": "release " "kind"},
                    "shape": [1],
                },
                "RELLAT1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT1",
                    "ncattrs": {
                        "long_name": "release " "latitude " "lower " "left " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLAT2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLAT2",
                    "ncattrs": {
                        "long_name": "release " "latitude " "upper " "right " "corner",
                        "units": "degrees_north",
                    },
                    "shape": [1],
                },
                "RELLNG1": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG1",
                    "ncattrs": {
                        "long_name": "release " "longitude " "lower " "left " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELLNG2": {
                    "dimensions": ["numpoint"],
                    "name": "RELLNG2",
                    "ncattrs": {
                        "long_name": "release " "longitude " "upper " "right " "corner",
                        "units": "degrees_east",
                    },
                    "shape": [1],
                },
                "RELPART": {
                    "dimensions": ["numpoint"],
                    "name": "RELPART",
                    "ncattrs": {"long_name": "number " "of " "release " "particles"},
                    "shape": [1],
                },
                "RELSTART": {
                    "dimensions": ["numpoint"],
                    "name": "RELSTART",
                    "ncattrs": {
                        "long_name": "release "
                        "start "
                        "relative "
                        "to "
                        "simulation "
                        "start",
                        "units": "seconds",
                    },
                    "shape": [1],
                },
                "RELXMASS": {
                    "dimensions": ["numspec", "numpoint"],
                    "name": "RELXMASS",
                    "ncattrs": {"long_name": "total " "release " "particle " "mass"},
                    "shape": [2, 1],
                },
                "RELZZ1": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ1",
                    "ncattrs": {
                        "long_name": "release " "height " "bottom",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "RELZZ2": {
                    "dimensions": ["numpoint"],
                    "name": "RELZZ2",
                    "ncattrs": {
                        "long_name": "release " "height " "top",
                        "units": "meters",
                    },
                    "shape": [1],
                },
                "WD_spec001": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "WD_spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "dquer": 0.6,
                        "henry": 0.0,
                        "long_name": "Cs-137_wet_deposition",
                        "units": "1e-12 " "kg " "m-2",
                        "weta": 7e-05,
                        "wetb": 0.8,
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "WD_spec002": {
                    "dimensions": ["nageclass", "numpoint", "time", "rlat", "rlon"],
                    "name": "WD_spec002",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "dquer": 0.6,
                        "henry": 0.0,
                        "long_name": "I-131a_wet_deposition",
                        "units": "1e-12 " "kg " "m-2",
                        "weta": 7e-05,
                        "wetb": 0.8,
                    },
                    "shape": [1, 1, 11, 30, 50],
                },
                "fptot": {
                    "dimensions": ["numpoint", "rlat", "rlon"],
                    "name": "fptot",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "long_name": "total_footprint",
                        "sampling_height": "undefined",
                        "units": "ng " "kg-1",
                    },
                    "shape": [1, 30, 50],
                },
                "level": {
                    "dimensions": ["level"],
                    "name": "level",
                    "ncattrs": {
                        "axis": "Z",
                        "description": "grid " "cell " "top",
                        "long_name": "height " "above " "ground",
                        "positive": "up",
                        "standard_name": "height",
                        "units": "meters",
                    },
                    "shape": [3],
                },
                "rlat": {
                    "dimensions": ["rlat"],
                    "name": "rlat",
                    "ncattrs": {
                        "axis": "Y",
                        "description": "grid " "cell " "centers",
                        "long_name": "latitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_latitude",
                        "units": "degrees",
                    },
                    "shape": [30],
                },
                "rlon": {
                    "dimensions": ["rlon"],
                    "name": "rlon",
                    "ncattrs": {
                        "axis": "X",
                        "description": "grid " "cell " "centers",
                        "long_name": "longitude " "in " "rotated " "pole " "grid",
                        "standard_name": "grid_longitude",
                        "units": "degrees",
                    },
                    "shape": [50],
                },
                "rotated_pole": {
                    "dimensions": {},
                    "name": "rotated_pole",
                    "ncattrs": {
                        "grid_mapping_name": "rotated_latitude_longitude",
                        "grid_north_pole_latitude": 43.0,
                        "grid_north_pole_longitude": -170.0,
                    },
                    "shape": {},
                },
                "spec001": {
                    "dimensions": [
                        "nageclass",
                        "numpoint",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "name": "spec001",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "decay": 7.3265155e-10,
                        "long_name": "Cs-137",
                        "ohreact": -9.9e-09,
                        "spec_ass": -9,
                        "units": "ng " "kg-1",
                        "vsetaver": -0.0003866022,
                        "weightmolar": -9.99,
                    },
                    "shape": [1, 1, 11, 3, 30, 50],
                },
                "spec002": {
                    "dimensions": [
                        "nageclass",
                        "numpoint",
                        "time",
                        "level",
                        "rlat",
                        "rlon",
                    ],
                    "name": "spec002",
                    "ncattrs": {
                        "coordinates": "lon " "lat",
                        "decay": 9.978277e-07,
                        "long_name": "I-131a",
                        "ohreact": -9.9e-09,
                        "spec_ass": -9,
                        "units": "ng " "kg-1",
                        "vsetaver": -0.0003866022,
                        "weightmolar": -9.99,
                    },
                    "shape": [1, 1, 11, 3, 30, 50],
                },
                "time": {
                    "dimensions": ["time"],
                    "name": "time",
                    "ncattrs": {
                        "calendar": "proleptic_gregorian",
                        "units": "seconds " "since " "2019-07-27 " "12:00",
                    },
                    "shape": [11],
                },
            },
        },
        "rotated_pole": True,
        "time_stats": {
            "max": 0.0023557064,
            "mean": 4.0843393e-06,
            "mean_nz": 2.9338966e-05,
            "median": 0.0,
            "median_nz": 3.3051265e-06,
        },
        "type": "Field",
        "var_setups": [
            {
                "combine_species": True,
                "deposition_type": "none",
                "domain": "auto",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "integrate": False,
                "lang": "de",
                "level": [0],
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "outfile": "dummy.png",
                "plot_type": "ens_median",
                "simulation_type": "ensemble",
                "species_id": [1],
                "time": [5],
                "variable": "concentration",
            },
            {
                "combine_species": True,
                "deposition_type": "none",
                "domain": "auto",
                "ens_member_id": [0, 1, 5, 10, 15, 20],
                "ens_param_mem_min": None,
                "ens_param_thr": None,
                "infile": "flexpart_cosmo-2e_2019072712_{ens_member:03d}.nc",
                "integrate": False,
                "lang": "de",
                "level": [0],
                "nageclass": [0],
                "noutrel": None,
                "numpoint": [0],
                "outfile": "dummy.png",
                "plot_type": "ens_median",
                "simulation_type": "ensemble",
                "species_id": [2],
                "time": [5],
                "variable": "concentration",
            },
        ],
    },
    "fig": {
        "axes": [
            {
                "bbox": {
                    "bounds": (60.0, 45.0, 930.0000000000001, 548.8946887110673),
                    "type": "TransformedBbox",
                },
                "type": "GeoAxesSubplot",
            },
            {
                "bbox": {
                    "bounds": (
                        60.0,
                        607.8446887110672,
                        930.0000000000001,
                        76.8452564195494,
                    ),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 607.8446887110672, 232.5, 76.8452564195494),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 348.37813190397634, 232.5, 245.51655680709092),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (1003.95, 45.0, 232.5, 289.4281319039763),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
            {
                "bbox": {
                    "bounds": (60.0, 28.533159338667986, 1176.45, 16.466840661332014),
                    "type": "TransformedBbox",
                },
                "type": "Axes",
            },
        ],
        "bbox": {"bounds": (0.0, 0.0, 1200.0, 900.0), "type": "TransformedBbox"},
        "type": "Figure",
    },
    "map_conf": {
        "geo_res": "10m",
        "geo_res_cities": "50m",
        "geo_res_rivers": "50m",
        "lang": "de",
        "lw_frame": 1.0,
        "min_city_pop": 300000,
        "ref_dist_conf": {
            "dist": 100,
            "pos": "bl",
            "type": "RefDistIndConf",
            "unit": "km",
        },
        "ref_dist_on": True,
        "rel_offset": [0.0, 0.0],
        "type": "MapAxesConf",
        "zoom_fact": 1.02,
    },
    "mark_release_site": True,
    "type": "Plot",
}
